### ISSUE TITLE
[Bug]: OFX Importer fails to recognize transactions in file

### ISSUE THREAD

**Issue by austempest** [actualbudget/actual#1007]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue

### What happened?

A bug happened!

Imported OFX file (direct export from bank. Bank wwas ING Direct (Australia).

### What error did you receive?

Import was successful, but please [file a bug report](https://github.com/actualbudget/actual/issues/new?assignees=&labels=bug%2Cneeds+triage&template=bug-report.yml&title=%5BBug%5D%3A+New+OFX+Importer:+bad+new+parse:) and attach a redacted version of the file so we can fix our new algorithm.

### Where are you hosting Actual?

Docker

### What browsers are you seeing the problem on?

Firefox

### Operating System

Windows 10

**Comment by austempest** [comment]
[Transactions(redacted).zip](https://github.com/actualbudget/actual/files/11414857/Transactions.redacted.zip)

**Comment by j-f1** [comment]
fyi @sinistersnare

**Comment by j-f1** [comment]
Thank you for reporting!

**Comment by tjfinlinson** [comment]
I noticed the same thing when importing my ofx files. I'm downloading from Zions Bank in Utah. I'll try and put a redacted file up here for use as well.

**Comment by tjfinlinson** [comment]
> Looking at this, it seems the old importer produced an import with 0 entries, and the new with 2. Because there was no explicit error, but only a diff, the old results were used (to ensure compatibility with past imports), and a warning was shown.
> 
> If the new importer was used, it would have succeeded as you would want. As the old results are used, you get the results you see here.

I'm not totally sure what this means, but are you saying that since the transactions are importing nothing is broken, just giving an error (or more of a notification) to say that Actual just sees the latest import as different previous ones? Will that message always show up, or will it eventually be removed?

That makes me think something didn't happen correctly and it might not have worked 100%.

Regardless, I'm attaching a redacted file in-case it helps in any way.


[Account-OFX-Transactions-Download-Redacted.txt](https://github.com/actualbudget/actual/files/11518630/Account-OFX-Transactions-Download-Redacted.txt)

**Comment by sinistersnare** [comment]
Currently there are 2 OFX importers use, the 'old' and the 'new'. In case of different results, 'old' is always used. However, in the case of this issue, 'new' would have been better.

In the future, if we remove the old parser and just use the new, this would have worked better.
