### ISSUE TITLE
[Bug]: Actual import error message claims errors are automatically reported

### ISSUE THREAD

**Issue by shall0pass** [actualbudget/actual#1069]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue

### What happened?

Found an error message that needs to be updated to point to GitHub rather than informing the user that the error is automatically reported.

FYI.  This was an attempt to import a 'new' test file since the hidden category feature was added into an older PR.  There should also be a note in the next release notes about a breaking change.

![image](https://github.com/actualbudget/actual/assets/20625555/4839d60e-6647-47bd-b020-c5f49738c347)

### Where are you hosting Actual?

Other

### What browsers are you seeing the problem on?

Chrome

### Operating System

Windows 11

**Comment by j-f1** [comment]
> FYI. This was an attempt to import a 'new' test file since the hidden category feature was added into an older PR. There should also be a note in the next release notes about a breaking change.


Currently, we do not support reverting migrations that have been applied to a file. That means that if you run a budget file with a newly added [migration](https://github.com/actualbudget/actual/tree/master/packages/loot-core/migrations), it can no longer be loaded in a previous Actual version. I’m not sure how we can best message this, since whether or not a release includes new migration(s) is generally independent of what new features it has (e.g. Nordigen integration requires no migration)
