### ISSUE TITLE
[Bug]: Mobile: blank space where account type used to be

### ISSUE THREAD

**Issue by trevdor** [actualbudget/actual#1163]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue

### What happened?

Accounts cards shown on mobile used to display the account type with an icon:
<img width="213" alt="before" src="https://github.com/actualbudget/actual/assets/5862724/988fb3ad-d864-4d93-ab16-8963311a674e">

That info is now gone:
![missing_account_type](https://github.com/actualbudget/actual/assets/5862724/7fce0241-9d84-427c-bfeb-cc81b1763f8e)

### What error did you receive?

none

### Where are you hosting Actual?

Other

### What browsers are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge

### Operating System

Mac OSX

**Comment by youngcw** [comment]
Isn't this because there are no longer account types? #948. #944

**Comment by trevdor** [comment]
Absolutely, @youngcw. I hadn’t realized that change went so far. 
Thanks for pointing it out.

**Comment by j-f1** [comment]
Reframing this and reopening it since it definitely feels like there’s an empty space there. Not sure if it would make more sense to make the rows shorter (would that make them too small to reliably tap?) or center the name or display some additional information (uncategorized transactions? balance change over the last month?).
