### ISSUE TITLE
[Bug]: File uploads in Safari don’t always do work the first time

### ISSUE THREAD

**Issue by mommyofavalor** [actualbudget/actual#1313]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue

### What happened?

A bug happened!

<img width="661" alt="Screen Shot 2023-07-08 at 9 46 00 AM" src="https://github.com/actualbudget/actual/assets/138994055/d61b9fe6-68ec-404a-aa24-d6ac383daa0d">

Every time I try to import transactions there are issues. Sometimes it wants me to double click on the file, sometimes it wants me to click once and press "upload". Sometimes neither of those work and I have to just try multiple times. Then, whenever it finally goes through I get an error message like the one above.

I am hosting on pikapod

### What error did you receive?

"possible error importing file"

### Where are you hosting Actual?

Other

### What browsers are you seeing the problem on?

Safari

### Operating System

Mac OSX

**Comment by j-f1** [comment]
Thank you for reporting!

> Sometimes it wants me to double click on the file, sometimes it wants me to click once and press "upload".

Both of these should work. The file picker is controlled entirely by the browser, so we don’t have any control over what happens here.

> Sometimes neither of those work and I have to just try multiple times.

I’ve seen this happen sometimes too in Safari, but haven’t been able to trace down exactly why it happens.

> Then, whenever it finally goes through I get an error message like the one above.

That error message comes from our new OFX parser, which we ultimately decided would be too complicated to update to work properly. The next release (v23.7.1 or v23.7.2), which will hopefully roll out to PikaPods soon, removes the new parser and falls back to our older, more reliable parser. You shouldn’t get those errors anymore after that update. In the meantime, you can ignore the message as it was just intended as a way for us to get feedback about files that broke our new parser (as it turned out, there were a lot!)

I’m going to retitle this issue to focus on the file upload issue since I think that’s the main thing we need to fix here.

**Comment by mommyofavalor** [comment]
Thank you for your quick reply, Jed. Makes sense and I appreciate all the
work that you are doing on Actual.

Maureen

**Comment by Cldfire** [comment]
++, I'm hitting this as well. I cannot upload a .csv file to import transactions from in Safari 16.5.2. Firefox 115.0.2 on the same laptop has no issues uploading a .csv file and importing transactions.

**Comment by j-f1** [comment]
Give #1345 a shot!

**Comment by Cldfire** [comment]
Poking at this, for whatever reason we don't seem to be hitting the conditional after awaiting the result of the file dialog:

https://github.com/actualbudget/actual/assets/13814214/196a7ec1-4234-4cc8-a7e3-51ba429ce0a8

**Comment by Cldfire** [comment]
Seems like Safari does not fire the `change` event listener when a file is selected in the dialog. Check out this codepen: https://codepen.io/udaymanvar/pen/MWaePBY?editors=1111

In Safari nothing is logged to the console after picking a file. In Firefox there are logs.

**Comment by Cldfire** [comment]
I ran `monitorEvents(document.body.querySelectorAll("input[type='file']"));` in the page console, and all of a sudden import is working fine in Safari and the `change` even is being fired on the file input.

I'm guessing WebKit doesn't like the fact that the file input is invisible, or something about it.

**Comment by Cldfire** [comment]
Ah hah, inserting the file input into the DOM seems to completely fix the problem in Safari. A simple `document.body.appendChild(input)` call leads to me being able to reliably import in Safari.

I guess WebKit doesn't like file inputs that aren't part of the DOM.
