### ISSUE TITLE
[Bug]: Double scrollbars

### ISSUE THREAD

**Issue by MatissJanis** [actualbudget/actual#1358]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue

### What happened?

There are 2x scrollbars in many pages (rules, schedules, budget, transactions, etc.). We should only have 1x scrollbar.

<img width="555" alt="Screenshot 2023-07-18 at 08 52 04" src="https://github.com/actualbudget/actual/assets/886567/45a95b68-a8fc-46d9-bfdf-bc5c07c1ad0b">

### Where are you hosting Actual?

None

### Operating System

None

**Comment by Avitus27** [comment]
Hi @MatissJanis I'd like to help with this issue. Could you add info on the browser and OS you're seeing this in so I can reliably replicate this? TIA!

**Comment by MatissJanis** [comment]
Latest chrome + OSX + always show scrollbars

<img width="324" alt="Screenshot 2023-07-18 at 18 13 13" src="https://github.com/actualbudget/actual/assets/886567/903a959f-7117-4cbf-99a7-0a2c9a2535e9">

**Comment by Kidglove57** [comment]
Thanks for confirming. I am on the latest OSX with "Always" enabled in OSX system settings for scroll bars.
I confirm that I am not seeing a double scroll bar in Chrome. Happy to help though with any info to troubleshoot this.

Here is what I see:
<img width="319" alt="CleanShot 2023-07-18@2x" src="https://github.com/actualbudget/actual/assets/93882449/0d036746-eebc-47b2-850c-af09a3b7537a">

**Comment by MatissJanis** [comment]
Do you have the browser maximized? It seems to be working correctly with the window mazimized, but if it's not maximized (and am using a laptop screen), then the two scrollbars appear.

**Comment by Kidglove57** [comment]
Good call. I can reproduce this now BUT:
1) NOT if I align the browser to either side of the screen (MacBook Air 15 inch) however narrow I make it.
2) ONLY if I align the browser to the bottom or top or the screen and reduce its height to just over half the height of the screen or less.

I was struggling for the right terminology there so hope it makes sense. In other words when the browser is in landscape view rather than portrait and reduced in height by about half.

**Comment by Avitus27** [comment]
I was able to reproduce under these settings & environment:
- Win 10
- Chrome 114.0.5735.134
- Display: 1920x1080 @ 14"
- 100% zoom, maximized window

I wasn't seeing this at first because I had my zoom set to 80%
I've also narrowed it down to a CSS style `.css-f0f5zh{ min-height:700px;}`, unchecking this in inspector removes the double scrollbar. Had a look around the code but I've no clue about Glamor, which seems to be how that CSS is generated. Sorry I can't be of more help here! 😓

**Comment by aleetsaiya** [comment]
I thought the purpose of the outer scrollbar is to make user to be able to scroll down to the page (not transaction table). When remove the `min-height: 700px`, it can make the outer scrollbar disappeared, but user will not be able to scroll down the whole page.

Do you think should we remove the outer scrollbar? This will make small screens user not able to scroll down to hide the title section (like "All Accounts" in the demo video)

Demo when I remove the `min-height` limit:

https://github.com/actualbudget/actual/assets/67775387/912ec105-274e-480b-bde5-541004ac9234

**Comment by MatissJanis** [comment]
Is there a way to set this according to the screen height? i.e. for smaller screens we would have the 2x scrollbars, but for bigger screens (think: all laptops and bigger) - we remove the double scrollbar.
