### ISSUE TITLE
Feature request: Schedule Income for the NEXT MONTH 

### ISSUE THREAD

**Issue by faspina** [actualbudget/actual#1381]
I get paid on the last day of the month , sometimes it hits on the 28ht or 29th. I want to designate this money to be utilized int he next month budget  rather than the current month.  
I would like to see a INCOME: NEXT MONTH category that push a July 28 paycheck to income for August 

YNAB was able to do this and it works very well

**Comment by Kidglove57** [comment]
@faspina 
Here is screenshot showing you the button - even if I had no further income to send to next month!

![image](https://github.com/actualbudget/actual/assets/93882449/27f2fc9a-fdf1-406c-a1ed-32601906cdb0)

**Comment by Kidglove57** [comment]
And here is the current documentation that included this feature (scroll down a bit):

https://actualbudget.org/docs/budgeting/

Very similar to YNAB 4

**Comment by faspina** [comment]
I got it working, thanks

**Comment by darthlite** [comment]
Related question I guess: Aside from manually inputting a new date, is there a way to get this month's income to show up as next month's income in reports and such?

If I receive income towards the end of November, but use it to budget for December, I would like to compare it to December's expenses.

**Comment by faspina** [comment]
I don't like the HOLD for next month option because I do have etra money after budget that I want to alocate to envelops but this amount is a paycheck. I like the idea of doing this at the transaction level , a tag that says use this next month maybe. With a stead y pay check every 30 of the month it would just be easier to do it this way

**Comment by shawalli** [comment]
I really like the way YNAB does it, where you can either assign to "Income: this month" or "Income: next month". The reason I like this approach better than the "hold" method is I don't need to do any math or special tricks to figure out how much money it available in the current or next month to budget. Additionally, when looking backward, you can easily see which income transactions are siloed into which months, rather than a floating level of money.

Having used AB for about 6 months now, it is one of the two features I still long for, because it makes the income management process dead-simple (at least as a user; I make no claims as to how it would be implemented behind the scenes).
