### ISSUE TITLE
[Feature] is it possible to post a schedule transaction to an account prior to its due date? 

### ISSUE THREAD

**Issue by faspina** [actualbudget/actual#1383]
### Verified feature request does not already exist?

- [X] I have searched and found no existing issue

### 💻

- [ ] Would you like to implement this feature?

### Pitch: what problem are you trying to solve?

Pitch:  I plan a full month in advance, we have consistent two pay checks in the family. 70% of those funds are fixed amounts. Mortgage,loans, not variable bills, etc.  I like to set my fixed expenses and incomes up ahead of time.  So I have a account called future transaction that contain the next month transaction, I just move them over to the Checking account usually two weeks at a time to match up with a paycheck so I can accurately track cashflow.  

for example I know the internet bill will come on July 18th and be 99.99 , I have a schedule transaction for july 18. but I cant post that transaction until 2 days before. While I could create it manually myself, I want to post it form the scheduled transaction screen. as the month of july begins so I can see all july expenses and income on the budget

FYI, I am trying to replace YNAB 4 and in YNAB 4 desktop version I can right click a schedule transaction and select enter in register regardless of the date

**Comment by radtriste** [comment]
@youngcw is that feature abandoned or replaced ?
I was looking it and trying to setup a PR for it because I don't understand why we could not post a transaction from a schedule whenever we want.
What would be the drawbacks of such a behavior ?

**Comment by youngcw** [comment]
@radtriste I don't think a PR for it would be an issue.  Mostly I was cleaning out old feature requests that have been just sitting.

**Comment by radtriste** [comment]
ok. Thank you. I will try to provide a PR soon.

**Comment by Kidglove57** [comment]
I agree that the two day window does seem very restrictive. The problem was partly addressed by adding a running balance in each account for upcoming scheduled transactions, so at least I always know what their impact is on my bank balance. The downside is that the schedules are only displayed a few days in advance which makes planning difficult. I would not want to post transactions ahead of them becoming real, so  my personal vote would be for scheduled transactions to instead be displayed for say a month in ahead, but with a toggle to close them so that they do not clutter the account register.

**Comment by radtriste** [comment]
Well the `post transaction` is something you do manually so each user is able to decide what is the best personal usage. There would be no added automation. Just the `post transaction` menu item available anytime instead of on due date.

I personally like to enter my schedule entries directly into my account to foresee my balance by the end of the month and be able to setup correctly my budget.
