### ISSUE TITLE
[Tech Debt] ButtonLink, LinkButton, ExternalLink, AnchorLink

### ISSUE THREAD

**Issue by MatissJanis** [actualbudget/actual#1414]
We have many components that act as fundamentally the same thing: a link.

- ButtonLink - button that uses react-router for internal app navigation
- LinkButton - a button that is styled in a specific way; this does not actually perform any navigation
- ExternalLink - `<a href>` element for links to outside of the app (open in new tab)
- AnchorLink - `<a href>` element for links inside the app (open in same window)

The goal of this ticket is to unify them. Before starting: please post the proposed interface in the comments.

**Comment by MatissJanis** [comment]
My recommendation:

Unify `ButtonLink`, `ExternalLink` and `AnchorLink` to a single component. And move `LinkButton` inside `button` with a new `type` (`Button` supports various styles - bare, primary, etc. - this could be another `type`).

**Comment by j-f1** [comment]
> Unify `ButtonLink`, `ExternalLink` and `AnchorLink` to a single component.

These are all pretty different components despite the similar name so I’m not sure this makes sense.

- `ButtonLink` has a completely different visual style than the others since it looks like a button instead of a link.
- `AnchorLink` is confusingly named and really only needed in the sidebar (its other usage site should be replaced with a plain `Link`). Its job is to change appearance when activated (this is how the current item in the sidebar turns purple). It should probably either be renamed or inlined into the `ItemContent` component. It doesn’t even end up really looking like a normal link.
- `ExternalLink` is specifically for _external_ links, ie not ones that go through React Router. I think being explicit about that is a good thing.

> And move `LinkButton` inside `button` with a new `type` (`Button` supports various styles - bare, primary, etc. - this could be another `type`).

Until recently, `LinkButton` just used `Button` and overrode it with styles. This had some strange effects, but I think merging it with Button directly could help since all the relevant code affecting its appearance is in one place.

**Comment by MatissJanis** [comment]
Conceptually they are all the same thing though: links. Maybe the underlying logic or styling is a bit different (external link vs internal react-router link), but conceptually they are the same thing. 

Think of it from a newcomers perspective. I (newcomer) want to add a new link. Should I use `ButtonLink`? Or `LinkButton`? Or perhaps `AnchorLink`? I don't know.

In an ideal world we would have a single **shared component** (highlight on the "shared" aspect; it's fine to have multiple variations internally, but not on the "shared" layer) for links that does some magic internally to convert it to button/a href/external link/etc.

(code snippet purely for illustration)
```
<Link to="/rules">Rules</Link>
<Link to="https://actualbudget.com" type="button">Docs</Link>
<Link to="/schedules" style={isActive ? activeStyle : inactiveStyle}>Schedules in nav</Link>
```

**Comment by th3c0d3br34ker** [comment]
Hi @MatissJanis, I would like to take up this issue. Since it Before starting, I wanted to have a quick discussion.
Here is what I plan to do:
- move `ButtonLink`, `ExternalLink` and `AnchorLink` to a single component called `Link`
- based on the `type` property (default: `link`) different components will be rendered.
- create a PR where I'll be posting the structure of the new `Link` component.

Please let know if your thoughts have changed on refactoring the Link component. Any suggestions are also appreciated.

**Comment by MatissJanis** [comment]
That sounds good. My recommendation would also be to first create this new
component and then move only 3x existing buttons/links to the new version
(all in a single PR). And then once we get the initial Link component
approved and merged - slowly migrate all the old ones to the new format.

We try to avoid massive PRs as they have a high risk of breaking things.

**Comment by th3c0d3br34ker** [comment]
hey @MatissJanis, I am glad to that I could contribute.

The remain task is to add `ExternalLink` component. Will be raising a PR for the same soon.


I wanted to ask about -- when/how do we address the usage of old components?

**Comment by MatissJanis** [comment]
> I wanted to ask about -- when/how do we address the usage of old components?

Up to you: if you want to do it, then feel free to perform the migration over a single (or multiple smaller) PRs. If not - I'd recommend adding a `@deprecated` comment to the old components with instructions how to port over to the new ones. And then hopefully someone else picks it up.
