### ISSUE TITLE
[Bug]: Split transaction deposits parent transaction amount to off-budget account instead of the child transaction amount

### ISSUE THREAD

**Issue by joel-jeremy** [actualbudget/actual#1574]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue

### What happened?

When splitting a transaction between an off-budget account and another payee, the whole transaction amount (100) is being deposited to the off-budget account instead of the the child amount (50):

![image](https://github.com/actualbudget/actual/assets/20313680/7a9c91e0-a836-46c4-9115-1c0f2cb91403)
![image](https://github.com/actualbudget/actual/assets/20313680/90733dc8-4f57-4065-a6ec-4994c0b42e71)

### Where are you hosting Actual?

Fly.io

### What browsers are you seeing the problem on?

Chrome

### Operating System

Windows 11

**Comment by kyrias** [comment]
More specifically, the problem here is that the creation of inverse transactions for transfers do not take split transactions into account.

To fix this properly I think what needs to be done is _not_ create inverse transactions where `is_parent` is true, and instead create them for the related child transactions.
