### ISSUE TITLE
[Bug]: Blank Transaction Can Now Be Added To Register

### ISSUE THREAD

**Issue by rich-howell** [actualbudget/actual#1627]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue

### What happened?

It now seems possible to enter a blank transaction into the transaction register without any details. I am almost sure that this wasn't possible before. 

![image](https://github.com/actualbudget/actual/assets/22135084/73101996-e4bc-424f-88b1-2435ee361c24)

This was replicated on https://demo.actualbudget.org/

### What error did you receive?

None

### Where are you hosting Actual?

None

### What browsers are you seeing the problem on?

Microsoft Edge

### Operating System

Windows 11

**Comment by jhonderson** [comment]
By looking at the table schemas, it seems like only account, amount and date fields are required: https://github.com/actualbudget/actual/blob/master/packages/loot-core/src/server/aql/schema/index.ts#L32-L54 (it's [been like that](https://github.com/actualbudget/actual/blob/4d9fdfc590e500c340bbcb4f09f2ec8681b97407/packages/loot-core/src/server/aql/schema/index.js#L32-L54) since the project went open source). Those 3 values are always present when creating a transaction from the UI. As as side note I see this behavior is the same in YNAB.

**Comment by Jackenmen** [comment]
Aside from maybe payee (and date which is already provided), I don't think a transaction needs to require any of the fields? There may perhaps be a reason for a lack of payee as well but I just can't think of one myself.

**Comment by rich-howell** [comment]
> Aside from maybe payee (and date which is already provided), I don't think a transaction needs to require any of the fields? There may perhaps be a reason for a lack of payee as well but I just can't think of one myself.

Fair enough - feel free to close
