### ISSUE TITLE
[Feature] Bank Sync - Recognise transfers between accounts

### ISSUE THREAD

**Issue by daniel-tp** [actualbudget/actual#1628]
### Verified feature request does not already exist?

- [X] I have searched and found no existing issue

### 💻

- [ ] Would you like to implement this feature?

### Pitch: what problem are you trying to solve?

I have set up bank sync via GoCardless for 2 accounts. I quite often do transfers between these accounts but when syncing these accounts to Actual, they are not recognised as transfers and have to be manually changed into transfers (Which usually creates a mess of duplicates as well).

It is possible to create rules that make certain payees into transfers, but this usually still doesn't connect transfers together.

This was initially proposed in https://github.com/actualbudget/actual/issues/724#issue-1609683346 but that was closed with the main bank sync feature was completed. 

There was also a PR created but never merged: https://github.com/actualbudget/actual/pull/766

### Describe your ideal solution to this problem

I would propose functionality to automatically recognise transfers going between accounts (Same amount, similar date) and connect them together. I realise this can't always be perfect but it would be better than having nothing.

### Teaching and learning

Hopefully this would be automatic, and just makes the Actual bank sync feature more seamless. Perhaps documentation on what to do when matching up transfers fails and possibly makes duplicates?

**Comment by M123-dev** [comment]
For me this is a core feature, not only normal transfers but also payments like

```Main Bank Accout -> Paypal -> Outgoing```

It would be nice if they were combined.

-------

Here some interesting information about transactions merging #669

**Comment by lucharo** [comment]
For me this a core feature too. Duplicate transfer transactions between accounts are very cumbersome to handle manually and prone to error.

**Comment by darianf01** [comment]
I would add to this wish another point. Some transfers are changing fees, but the fee is not added as separate transaction. So sending from source account A 100cocoswith 2cocos for transfer, but debiting the destination account B 100cocos. The payment appears as 102cocos in account A. Would be nice if such transfers can still be automatically matched.

**Comment by CelestialStreamer** [comment]
I have about a dozen automatic transfers a month, and I usually make at least another dozen more a month manually transferring (usually paying off credit card). I'm new to using Actual and found it tedious to make sure all my accounts (25+) were all correct (reconciled). I haven't even re-synced with SimpleFIN for fear of making a lot of work for me to do.

**Comment by musicaldesigner** [comment]
In YNAB, if I change a transaction to a transfer, it automatically recognizes the duplicate in the other account and merges them, so that could be an alternative or additional solution which is only partially automatic.

I transfer between my accounts daily. Actual is almost unusable for me until this is implemented since I have so many transfers in my accounts.

**Comment by KonPaw** [comment]
Fyi as a workaround you can add rules that do this. On one account I set Actualbudget to change it to transfer. And on the receiving one I set a rule to delete transactions from that source.

**Comment by JacobGa03** [comment]
> Fyi as a workaround you can add rules that do this. On one account I set Actualbudget to change it to transfer. And on the receiving one I set a rule to delete transactions from that source.

Yes, I believe this is the best way.

For instance, you create a rules in the accounts which will be paying the other (ie. the account which initiates the transfer, let's call it account A) **and** the receiving account (ie. the account receiving the funds, let's call it account B).

Create a rule for account A wherein when the imported payee matches the payee you want to transfer to, then we set the transaction as a transfer. This is useful when wanting to move money from savings to checking (or vise versa) or when paying off a credit card.

Create a rule in account B wherein the imported payee matches the transaction you want to be matched in the transfer (this might appear as a "Transfer" or "Payment received") and set this transaction to be deleted. This ensures that the transaction isn't duplicated in account B when the first rule we created is ran; because when we create the transfer two transactions will appear (one in account A and another in account B).

Hope this worked out explanation makes sense. Happy budgeting! :)

**Comment by juanpagg15ug** [comment]
I wanted to share some practical findings and lessons learned from developing an automated ingestion and transfer engine for Actual Budget across multiple bank accounts.

### 1. A word of caution on the "Rule + Delete" workaround
The workaround suggested above (Rule on Account A creates a Transfer, Rule on Account B deletes the incoming transaction) seems clever at first, but in practice, it carries a **high risk of silent data loss**:
- **The Sync Race Condition**: If Account B syncs or receives the webhook/statement *before* Account A, Account B's rule will trigger and **delete the incoming transaction immediately** before Account A has even created the counter-transfer. Your balance will be off, and finding which transaction went missing is painful.
- **False Positives**: If an external third party sends funds with a similar payee description, a blanket `delete` rule will wipe out genuine money.

### 2. The Root Cause: Why fuzzy matching inside Actual core is difficult
A common suggestion is fuzzy matching (amount + date window $\pm 3$ days). However, this is notoriously tricky in core Actual:
- **Fees & FX**: Outflows and inflows often don't match exactly (e.g. Q102 debit with a Q2 fee vs. Q100 credit on the destination).
- **Lack of Institutional Identity**: Unlike YNAB (which natively tracks account/routing numbers and institutional IDs), Actual intentionally keeps accounts lean, minimal, and provider-agnostic. Inside Actual's database, an account is just an ID and a string name.

### 3. How we solved this reliably (The Middleware / Metadata Approach)
Instead of modifying Actual’s core database or relying on destructive deletion rules, we built an ingestion middleware using `@actual-app/api` that solves the problem **at the ingestion boundary before transactions enter the ledger**:

1. **Account Identification via Name Metadata**:
   Without altering Actual's SQLite schema, we embed institutional metadata directly into account names using a bracket convention:
   `Checking [Bank|Product|Currency|AccountNumber|Tag]` (e.g. `Monetaria BI [BI|Monetaria|GTQ|09261340422|#Checking]`).
2. **Deterministic Matching in Middleware (`TransferEngine`)**:
   When an event arrives (ACH notification email, SMS, or export), the raw source almost always contains both the origin and destination account numbers.
   - The engine parses `sourceIdentifier` and `destinationIdentifier`.
   - It matches both against the bracket metadata of existing accounts via `api.getAccounts()`.
3. **Direct Native Transfer Creation**:
   If both accounts belong to you, the engine doesn't insert two unlinked transactions. Instead, it injects a single payload with `payee_id = destinationAccount.id`.
   Because of how Actual works under the hood, setting `payee_id` to another account's ID automatically creates a **flawless, native, two-way linked transfer**.
4. **Idempotency**:
   Deduplication is handled upstream using unique confirmation IDs or SHA-256 hashes (`imported_id`), completely eliminating the need for `delete` rules.

### Takeaway for Upstream / Sync Providers
If this is to be tackled natively in Actual or within sync providers (GoCardless/SimpleFIN/Pluggy), the most robust solution is **not** post-import heuristic guessing (amount + date window), but allowing sync providers to map **institutional account numbers to Actual accounts**. When a transaction's counterparty account number matches another connected account, the sync provider should inject it directly as an internal transfer (`payee_id`).

**Comment by jfdoming** [comment]
> I wanted to share some practical findings and lessons learned from developing an automated ingestion and transfer engine for Actual Budget across multiple bank accounts.
> 
> ### 1. A word of caution on the "Rule + Delete" workaround
> The workaround suggested above (Rule on Account A creates a Transfer, Rule on Account B deletes the incoming transaction) seems clever at first, but in practice, it carries a **high risk of silent data loss**:
> 
> * **The Sync Race Condition**: If Account B syncs or receives the webhook/statement _before_ Account A, Account B's rule will trigger and **delete the incoming transaction immediately** before Account A has even created the counter-transfer. Your balance will be off, and finding which transaction went missing is painful.
> * **False Positives**: If an external third party sends funds with a similar payee description, a blanket `delete` rule will wipe out genuine money.
> 
> ### 2. The Root Cause: Why fuzzy matching inside Actual core is difficult
> A common suggestion is fuzzy matching (amount + date window ± 3 days). However, this is notoriously tricky in core Actual:
> 
> * **Fees & FX**: Outflows and inflows often don't match exactly (e.g. Q102 debit with a Q2 fee vs. Q100 credit on the destination).
> * **Lack of Institutional Identity**: Unlike YNAB (which natively tracks account/routing numbers and institutional IDs), Actual intentionally keeps accounts lean, minimal, and provider-agnostic. Inside Actual's database, an account is just an ID and a string name.
> 
> ### 3. How we solved this reliably (The Middleware / Metadata Approach)
> Instead of modifying Actual’s core database or relying on destructive deletion rules, we built an ingestion middleware using `@actual-app/api` that solves the problem **at the ingestion boundary before transactions enter the ledger**:
> 
> 1. **Account Identification via Name Metadata**:
>    Without altering Actual's SQLite schema, we embed institutional metadata directly into account names using a bracket convention:
>    `Checking [Bank|Product|Currency|AccountNumber|Tag]` (e.g. `Monetaria BI [BI|Monetaria|GTQ|09261340422|#Checking]`).
> 2. **Deterministic Matching in Middleware (`TransferEngine`)**:
>    When an event arrives (ACH notification email, SMS, or export), the raw source almost always contains both the origin and destination account numbers.
>    
>    * The engine parses `sourceIdentifier` and `destinationIdentifier`.
>    * It matches both against the bracket metadata of existing accounts via `api.getAccounts()`.
> 3. **Direct Native Transfer Creation**:
>    If both accounts belong to you, the engine doesn't insert two unlinked transactions. Instead, it injects a single payload with `payee_id = destinationAccount.id`.
>    Because of how Actual works under the hood, setting `payee_id` to another account's ID automatically creates a **flawless, native, two-way linked transfer**.
> 4. **Idempotency**:
>    Deduplication is handled upstream using unique confirmation IDs or SHA-256 hashes (`imported_id`), completely eliminating the need for `delete` rules.
> 
> ### Takeaway for Upstream / Sync Providers
> If this is to be tackled natively in Actual or within sync providers (GoCardless/SimpleFIN/Pluggy), the most robust solution is **not** post-import heuristic guessing (amount + date window), but allowing sync providers to map **institutional account numbers to Actual accounts**. When a transaction's counterparty account number matches another connected account, the sync provider should inject it directly as an internal transfer (`payee_id`).

Quick reminder about our [AI policy](https://actualbudget.org/docs/contributing/ai-usage-policy#interacting-with-maintainers-should-be-human).
