### ISSUE TITLE
[Feature] Add notes to mobile view

### ISSUE THREAD

**Issue by barart** [actualbudget/actual#1764]
### Verified feature request does not already exist?

- [X] I have searched and found no existing issue

### 💻

- [ ] Would you like to implement this feature?

### Pitch: what problem are you trying to solve?

You need to press every transaction to see the notes of it, i think notes information is important and is only the missing info of every transaction on the account view, you need to press the transaction itself to see the notes

### Describe your ideal solution to this problem

The lates version show every transaction as this:

=========================
Date
=========================
Payee                             $0.0000
Category
==========================

It would be nice to add the notes maybe between payee and category with small letter too like this:

=========================
Date
=========================
Payee 
Notes                                      $0.0000
Category
==========================

### Teaching and learning

ADding a view to use less clicks/tabs on mobiles would be very useful and informative to see fast almost all the important info everybody want to see on the transactions

**Comment by joel-jeremy** [comment]
Added in https://github.com/actualbudget/actual/pull/1964

**Comment by Teprifer** [comment]
@joel-jeremy I think you may've mis-read? 

1964 covers category and group notes, this issue is for transaction notes.

To put in image form:

Current: 
![image](https://github.com/actualbudget/actual/assets/34882928/71bba40b-df33-431d-8be2-9fbe6b3a2dd2)

Proposed:
![image](https://github.com/actualbudget/actual/assets/34882928/ebcb713b-8400-4476-9107-e62574b6c75d)

**Comment by barart** [comment]
@Teprifer Thanks! thats exactly, @joel-jeremy
