### ISSUE TITLE
[Feature] Flags, which can add detail to expenses

### ISSUE THREAD

**Issue by relima** [actualbudget/actual#1898]
### Verified feature request does not already exist?

- [X] I have searched and found no existing issue

### 💻

- [ ] Would you like to implement this feature?

### Pitch: what problem are you trying to solve?

Enhance your budgeting experience with the Flags feature, which can add detail to expenses, help track reimbursements, and color-code related transactions. Learn how to name, add, change, and remove flags from transactions, and how to search by flag. Note that flags are an optional feature— your budget can be successful with or without them!

### Describe your ideal solution to this problem

**What Can I Do With Flags?**
Looking to add some extra detail to your expenses? Want to really dial in on tracking reimbursements and shared expenses? Try out our Flags feature! Flags can serve multiple functions in your account register and budget as a whole, including:

Adding detail to your expenses, color-coding related transactions. Flags help group expenses that have separate categories, like tax-deductible expenses. You can also [export your flagged transactions] and then share them with anyone who will listen to you.

Helping you follow up on reimbursable expenses (who owes you, or what it's for). 

If you're budgeting with a partner, you can flag transactions that you need to discuss together.

Reminders to take action, like remembering to pay a bill that isn't on autopay.

If you're frequently needing to get a total amount that you've spent on something—but the transactions span multiple categories or accounts—using a flag allows you to search for the flag color, and get a selected total with ease.

Adding splashes of color to your accounts and transactions!

### Teaching and learning

This is on YNAB4. Really useful feature.

**Comment by Shazib** [comment]
You can sort of emulate this by putting things in the notes column, e.g. #taxdeductible

You can filter by those 'tags' then. Maybe we could support colouring things using tags we well as a sort of quicker way of achieving things.

**Comment by joel-jeremy** [comment]
I think the idea is the same with the one proposed in this issue: https://github.com/actualbudget/actual/issues/531

**Comment by shawalli** [comment]
> I think the idea is the same with the one proposed in this issue: #531

I disagree, specifically because of the YNAB callout. I think this request is for colored flags. The idea is to use a simple visual indicator for the purposes of highlighting transactions in a list view for further review of some kind. For instance, I used flags in YNAB for FSA/HSA-eligible expenses. For my system, blue meant I had scanned the document and purple meant I had submitted for reimbursement. I _also_ then used an `#hsa` tag in the memo field to allow filtering of all of these kinds of transactions.

For reference, here is a screenshot of the empty flag field and flag dropdown in YNAB:

![image](https://github.com/actualbudget/actual/assets/2999598/ecee5f88-2828-44fb-be58-d6f9d751a78c)

If you've used Gmail, you can see the same idea with the flag/star/important buttons in the inbox view.

**Comment by truncsphere** [comment]
I would love to see traction on this request. I'm in the process of migrating to Actual Budget and this a necessary component that will make a world of difference. 

For me personally, I use flags to highlight which transactions on my credit card have not yet been paid off yet. In addition, I have an off-budget account that I use sometimes to pay a specific CC transaction, for this I use a specific flag color as well.

**Comment by shawalli** [comment]
This could be extended even further by allowing a single emoji character of any kind to allow more categorization rather than a small list of pre-selected flags

**Comment by relima** [comment]
Any news here? This is the only feature I still miss from ynab

**Comment by Mansarde** [comment]
@joel-jeremy 
> I think the idea is the same with the one proposed in this issue: [#531](https://github.com/actualbudget/actual/issues/531)

This is not a duplicate, as explained by shawalli 
We can add any tag to a note, sure. But we can't easily replace it. Having a separate state-flag that can highlight transactions (similar to YNAB as others mentioned) would be super helpful.

Can you kindly re-add the `needs-votes` label? 🙏

**Comment by relima** [comment]
Oh, I want this feature so so much. Only thing still holding me back on ynab4

**Comment by Shazib** [comment]
Can you currently add a # tag with an emoji? could we add improved features for searching, sorting, replacing & filtering onthe existing tags? 

🟦🟥 etc could then be used

**Comment by Mansarde** [comment]
> Can you currently add a # tag with an emoji? could we add improved features for searching, sorting, replacing & filtering onthe existing tags?
> 
> 🟦🟥 etc could then be used

Yeah adding colors as # tags works, and it's relatively easy to add them to a note.
(i.e. select multiple transactions, press N, choose "prepend" and enter the # tag).
But it's not really possible to replace them easily, as the note dialog's "replace" field seems to just replace the entire note.

Regex in the note-dialog's replace field would help, but be quite cumbersome just to replace a tag.
The note-dialog could have a dropdown just for tags (or perhaps instead at the top of the table), which lists the tags on the selected notes and allows to remove and add new ones.

**Comment by Shazib** [comment]
> > Can you currently add a # tag with an emoji? could we add improved features for searching, sorting, replacing & filtering onthe existing tags?
> > 
> > 🟦🟥 etc could then be used
> 
> Yeah adding colors as # tags works, and it's relatively easy to add them to a note.
> (i.e. select multiple transactions, press N, choose "prepend" and enter the # tag).
> But it's not really possible to replace them easily, as the note dialog's "replace" field seems to just replace the entire note.
> 
> Regex in the note-dialog's replace field would help, but be quite cumbersome just to replace a tag.
> The note-dialog could have a dropdown just for tags (or perhaps instead at the top of the table), which lists the tags on the selected notes and allows to remove and add new ones.

Yeah maybe we could have a more intelligent tag manager type system that serves all needs? 

Not opposed to separate flags I just feel like I see a lot of feature creep in actual

**Comment by shawalli** [comment]
> Yeah maybe we could have a more intelligent tag manager type system that serves all needs? 
> 
> Not opposed to separate flags I just feel like I see a lot of feature creep in actual

If that is being considered, I'd like to include #3266 in the discussion as well.

**Comment by shawalli** [comment]
I took a stab at implementing this, but wanted some community feedback before continuing down the implementation path.

![Image](https://github.com/user-attachments/assets/6d81bacd-8a35-40ca-9678-d9768a9ebf70)

I plan to make the database changes and initial implementation (what you see above) in a first PR, then tackle the filter/match capabilities and rules/schedules afterwards.

**Comment by relima** [comment]
OMG, @shawalli. Thank you, thank you, thank you. This is the only feature I miss that has been holding me back from migrating from YNAB4. It looks fantastic!

**Comment by relima** [comment]
Just giving you a bit more insight of why this is so important to me, it is because this is how I am able to tell if a bill has been scheduled but not yet paid (yellow). Or if I have it paid before being due (green). Or if the amount I have been charged does not match what I was expecting (red).. and so on. I use it a lot.

**Comment by shawalli** [comment]
Take a look at the PR and left me know what you think

**Comment by shawalli** [comment]
At @MatissJanis request, I am writing an RFC for flags to clarify their function and use as a separate feature from tags.

----------

# RFC: Transaction Flags

## Problem Statement

When doing accounting-type tasks during budgeting, there is often a need to mark the state of a transaction. When reviewing transactions, reconciling missing items, tracking transactions as needing reimbursement/submitted/reimbursed, and more, it is useful to have a quick visual indicator that is applied to one or more transactions with a single click.

Actual currently offers tags as inline text-based `#tags` in Notes. Tags are powerful but text‑driven, and not optimized for these transient workflow states or bulk operations. Tags are useful for persistent organization, where the notes field is relatively stable once the transaction is filled in. Competing tools (YNAB, Copilot, Mint, etc.) augment categories with visual flags or visual tags that support quick visual scanning, state tracking, and bulk editing.

## User Stories

1. **Reconciliation**: As a user reconciling my bank statement, I want to mark transactions as 'verified' with a single click so I can visually mark off transactions without switching views or editing text fields.

2. **Reimbursement tracking**: As a user who submits work expenses, I want to track 🔴 needs-attention → 🟡 submitted → 🟠 approved → 🟢 reimbursed states so I can confirm nothing was missed, and change state with one click instead of editing notes text.

3. **Bulk review**: As a user catching up on 50+ imported transactions, I want to flag items needing attention, then clear flags as I work through them, without losing my selection if I need to check another account.

4. **Mixed semantics**: As a user organizing a work trip dinner, I want to use `#Conference2026` for reporting while also flagging the transaction as 'awaiting reimbursement,' so the tag persists for historical purposes while the flag tracks temporary state.

## Goals

1. Provide mechanism for quick, visual changes to transactions.
2. Support basic set of unique visual indicators that can be applied to the transactions.
3. Native support for the feature, including hotkeys and key-based navigation.
4. Provide hook for future custom flags specifically for budgeting (e.g. flags to represent different stages of reimbursement, reconciliation flags, etc)

## Non-Goals

1. Flags do not replace tags.
2. Tags remain the primary tool for project, organization, and report‑oriented grouping.

## Proposed Solution

Flags are implemented as a new field on transactions. Only one flag is permitted per transaction, and it is stored in such a way as custom/future flags can also be stored on the transaction. Flags are intentionally limited and low‑friction, optimized for status and attention, not complex organization or rich classification.

Emojis align with Actual’s existing visual, table‑driven UI and allow user‑defined workflows (e.g., 🧾, 🟡, ❓, 🔍) without requiring additional configuration screens. This keeps implementation scope reasonable while still providing structured state distinct from free‑form notes and without requiring entering the notes field and typing or deleting notes.

## Alternatives Considered

The primary alternative is using the notes field for this feature (e.g., structured tag dropdown, dedicated tag column), but this conflates two distinct use cases:

| Dimension | Tags | Flags |
|-----------|------|-------|
| **Lifetime** | Persistent (months/years) | Transient (hours/days) |
| **Cardinality** | Many per transaction | One per transaction |
| **Purpose** | Classification & reporting | Workflow state |
| **Customization** | Open-ended | Small, finite set |
| **Interaction** | Type| Click/toggle |

I did give this a try myself, but concluded it is more clunky and tedious for the following reasons:

* Single Transaction
  * To make changes to an individual transaction, I need to click into the notes field and type out (or delete) the tag.
  * If the notes field is too long, the tag itself is hidden from view.

* Multiple Transactions
  * To make bulk changes (e.g. reconciliation), I needed to select each transaction, then use the bulk tag editor to add or remove the tag.
  * The same problem occurs here if any of the notes field are too long.
  * Additionally, I am now locked to the current view until I bulk-edit the tag. If I need to switch to a different view for any reason, I now need to decide whether to bulk-edit the tag first, or lose my selection when I return to the view.

## Risks / Tradeoffs

The main cost of this implementation is that it does require adding a new column to the transaction data type. Because the value of the column is constrained to a specific type of data, it should be relatively basic.

## References

- https://www.reddit.com/r/ynab/comments/1ixv2oc/how_do_you_track_reimbursed_expenses/
- https://www.reddit.com/r/ynab/comments/10a0dbm/flags_how_do_you_use_them_improvements_you_want/
- https://www.youtube.com/watch?v=m8moXI3APkQ
- https://www.youtube.com/watch?v=MLNQ5eUWRhM
- https://www.reddit.com/r/ynab/comments/194ikcj/do_you_use_flags_if_so_what_for/
- https://www.reddit.com/r/ynab/comments/1glh7j4/ynab_flag_usesother_advice/
- https://support.ynab.com/en_us/flags-a-guide-Skh8Xb4kj

**Comment by MatissJanis** [comment]
Thanks @shawalli ! What is your specific problem that flags would solve? I think I am missing the context on your specific user issue. It would be useful to know that.

**Comment by youngcw** [comment]
What about tags isn't suited for bulk operations?  The notes field can be bulk edited and the editing abilities are very capable. You can do append, prepend, replace, and find and replace with optional regex.

**Comment by truncsphere** [comment]
For me personally I would use colored flags to mark transactions temporarily. Editing the notes field for tags is just not practical or wife friendly. 

Use cases:
- Flag transactions on a CC that haven't been payed yet
- Some transactions are flagged a certain color if they are to be payed by a "Joint" account, another color if it's from our personal account/other
- Flag manually entered transactions that have not yet cleared so I don't pay them until it's cleared

Currently in YNAB we make use of 3/4 different flag colors. Each of us know exactly what each color represents.

**Comment by Shazib** [comment]
Whilst i understand the desire I don't think its really worth the added complexity of another column in teh transaction table, in the db etc for something that pretty much already works via notes.

One issue with using tags in notes is that you can't see them at a glance, if you've appended it, maybe it would be nice if the cut-off for notes '...' was intelligent and cut around tags. You can put emojis in the tags so you could do # + 🟥🟧🟩🟦🟪🟫⬛⬜ but you cant see it with a longish note comments. 

<img width="500" height="88" alt="Image" src="https://github.com/user-attachments/assets/b0144f30-e910-44cc-a8fa-0e4b7b01998e" />

**Comment by Shazib** [comment]
+ the possible fix? 

<img width="453" height="87" alt="Image" src="https://github.com/user-attachments/assets/258d82ec-188f-4340-a853-425eef283530" />

Or maybe some option to be able to left-align all tags at the start, and then when you click into the note it shows you the full formatted text? Something like that anyway, as i run into this issue with other regular text based tags anyway.

**Comment by MatissJanis** [comment]
> Thanks [@shawalli](https://github.com/shawalli) ! What is your specific problem that flags would solve? I think I am missing the context on your specific user issue. It would be useful to know that.

re-read the conversation above and this was actually already answered: "For instance, I used flags in YNAB for FSA/HSA-eligible expenses. For my system, blue meant I had scanned the document and purple meant I had submitted for reimbursement.".

--

I'm not opposed to the idea of flags. There is certainly some merit to the idea. Especially if we make it usable via emojis (so a very long list of unique "flags"). However, I'm not yet certain if this fits into the core product, or if a better spot for it would be in a plugin (once we have these 🙏). The votes on the core message would help understand the appetite for this and thus help us make an informed decision.

**Comment by shawalli** [comment]
The part I'm struggling with is why there is a desire to shoehorn as many use cases into tags as possible. I would guess than most emigrants from YNAB know what flags are and how to use them, and think of them differently than tags. Tags look and behave more like static ways to slice and dice the data when doing searches. Flags provide temporary identification and are prominent visible and easy to interact with to quickly change when performing processes like statement reconciliation, reimbursement, etc.

At this point, I'm content not to have this merged into the code base and just keep it on my fork, as it is already providing me value. But I have to wonder why there is such a resistance to incorporating something that is already a well-established use case on competing platforms that users (besides just me...look at the few issues closed as clones and linked to this one, posts in discord) are asking for.

**Comment by truncsphere** [comment]
Editing the notes field for a temporary "flag" is not practical. Additionally, if you use SimpleFIN it often overwrites the notes field making it hard to trust the reliability of this field. 
Personally, I use notes for what the transaction was or add a tag if a transaction was part of a vacation/trip, etc.

**Comment by nikhilweee** [comment]
I very much agree that the Notes section is trying to act like a catch all field for different functionalities.
1. It contains transaction description from SimpleFIN
2. If a user decides to tag a transaction, they need to edit the notes section
3. If a user decides to edit the description from SimpleFIN, again - edit notes.

I'm coming from monarch money which has separate fields for all three - tags, description (imported from sync provider) and notes (added by user manually). And I have to say I very much enjoy the separation. I know this thread is about adding a separate flags column to transactions but the sentiment here is very much the same.
