### ISSUE TITLE
[Bug]: Cant change amount sign from negative in schedule on firefox

### ISSUE THREAD

**Issue by youngcw** [actualbudget/actual#1922]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue

### What happened?

When setting up or editing a schedule in firefox the amount cant be changed to positive.  It works fine in Chrome browsers.  If you click it, nothing happens when it should change between '-' and '+'.

### What error did you receive?

no error, it just doesn't work

### Where are you hosting Actual?

None

### What browsers are you seeing the problem on?

Firefox

### Operating System

None

**Comment by miqh** [comment]
Here's a snippet of interest:

https://github.com/actualbudget/actual/blob/93922567fc5ec3952e60203a04a2cb7c1821fe70/packages/desktop-client/src/components/util/AmountInput.js#L71

Firefox is (correctly, IMO) respecting the `disabled` state of the sign toggling button.

On the other hand, Chromium appears to trigger the pointer-related event handlers irrespective of `disabled`.

`focused` is also a prop to the `AmountInput` and it's never changed.

When the sign toggle button is forcefully enabled, interaction looks like this:

![1](https://github.com/actualbudget/actual/assets/43751307/f26cab62-0139-481e-8987-1b0509af85d7)

I'm unsure what the best intervention here is, especially since `EditSchedule` doesn't appear to maintain a `focused` state.
