### ISSUE TITLE
"Create Rule" from payees modal does not add conditions

### ISSUE THREAD

**Issue by winklevos** [actualbudget/actual#195]
When using "Create Rule" button from the payees modal I would expect the rule to populate the condition for that payee. This doesn't occur, meaning you need to manually add it, the modal has no context so you would also need to remember the payee to search.

Browser: firefox
Version: https://hub.docker.com/r/kippenhof/actual-server 
Confirmed the same behaviour locally building from master  

![image](https://user-images.githubusercontent.com/30995408/185774002-040cef9e-9c4a-4e2f-aa07-2631a5d217ee.png)

![image](https://user-images.githubusercontent.com/30995408/185774022-2c5bab99-d028-499a-9830-7ca82cfd4a94.png)

I would expect
![image](https://user-images.githubusercontent.com/30995408/185774064-e0263dc2-7adf-4c07-94ee-2727c4b0a83d.png)

**Comment by rich-howell** [comment]
Hey @winklevos 
 
I am not sure this is a bug, but I will go ahead and mark it as such for the time being until it can be confrirmed either way. 

Cheers

**Comment by winklevos** [comment]
Only reason I have the expectation it would populate is because there is a "create rule" button for each payee row. So seemed context bound. 

Might be another UX thing if it was never intended

**Comment by Kidglove57** [comment]
I am a bit puzzled. I have just entered two transactions in Actual for long standing payees and the category populated itself automatically - no problems. This is possibly becomes I am a long term user of Actual. My understanding has always been that Actual watches for a pattern over several  transaction entries for a particular payee and only then starts to auto populate the category. Of course I never want an Amazon payee to do this because the category is different every time, so I manually switch it off for some payees (by setting the category in the rule to "nothing"). On a number of occasions I have also edited a particular payee to add the categorisation or note rule that I really want.

What I have not been able to find out is the exact logic for when a rule gets added to a payee. I just added the same new payee test transaction three times in a row and no rule was created so I am guessing it is more complex than that!

**Comment by rich-howell** [comment]
@Kidglove57 This is exactly how I understood that it worked, try creating a transaction for a fictional payee, I bet you don't get a rule created.

**Comment by Kidglove57** [comment]
Correct - and that is exactly what I was testing. Nor does it create a category for a payee I have only used once before. But no problem in overriding that if I want to - by adding a rule right away.

**Comment by winklevos** [comment]
I think you're meaning to comment related to https://github.com/actualbudget/actual/issues/196.


This ticket is a UX thing unrelated to auto creation of rules

**Comment by Kidglove57** [comment]
Thank you for linking the two issues. Sorry for the confusion

**Comment by Kidglove57** [comment]
Returning to the issue actually raised here - I totally see the point made about the payee not auto populating when creating a rule relating to that payee. I agree that this would be expected behaviour. I see that there is the option to add multiple conditions ("is" or "one of") before apply any particular action so possible this is an unintended consequence of the flexibility given by the rule structure?

**Comment by neilmccreery** [comment]
I'm on version 23.1.12 with image `ghcr.io/actualbudget/actual-server:latest` and I am still experiencing this issue. Can anyone help?

**Comment by rich-howell** [comment]
> I'm on version 23.1.12 with image `ghcr.io/actualbudget/actual-server:latest` and I am still experiencing this issue. Can anyone help?

This will be available in the next release of Actual. You can find everything available in the current release, here https://actualbudget.github.io/docs/Release-Notes/
