### ISSUE TITLE
[Feature] Feature request

### ISSUE THREAD

**Issue by Teifun2** [actualbudget/actual#1978]
### Verified feature request does not already exist?

- [X] I have searched and found no existing issue

### 💻

- [X] Would you like to implement this feature?

### Pitch: what problem are you trying to solve?

My Income comes relatively late in the month. I want to Budget this always for the next month only.

What im currently doing is every month, i "hold for next Month" the exact value that was in my Income tab.

Ideally this could be setup automatically, so that this additional action is not required.

### Describe your ideal solution to this problem

Similar to the "Rollover Overspending" of the Expenses total, i would like to have the option to indicate which category in the incomes should be automatically set aside for next months budget.

### Teaching and learning

After i discovered the "Rollover Overspending" feature i naturally searched for the this feature. As it would be interacted with the same way (click on total value of month to activate) i hope users would find it quickly.

https://actualbudget.com/docs/budgeting/how-it-works/ This documentation would need an additional paragraph, maybe below: **Rollover negative category balances** 
to explain the "Hold for next Month" of the Income!

**Comment by Teifun2** [comment]
Would this be approved if i could do it in a PR?

Any poiners to understand what would be needed to do it.

**Comment by jrucker2004** [comment]
I also think the way income is handled needs some work, but I don't know the best way to go about it.  I'm self employed, and my income comes in gradually throughout the month, so it's really difficult to see what I'm working with ahead of time.  My current solution is to create a new account called "Projections" and a category called "Projected income".  I then add a transaction for what I predict what I'll have for income for the current or next month, and adjust it as the month progresses.  I also have some income for contract work that takes 4-6 weeks to pay out.  I need to be able to budget with that money, so I add it to my projections account, then delete it when the money actually shows up.

I'd love to be able to budget multiple months out, but since income can't be "Budgeted" like expenses are, I have to fake it with my projected transactions.

**Comment by Kidglove57** [comment]
@jrucker2004 in the circumstances you describe I can totally understand you wanting to project forward your income and expenditure.

There is a conflict here with Actual’s fundamental budgeting principle (Envelope Budgeting). This mirrors the way our forebears used to put money into physical envelopes dedicated to each expense category. Since envelope budgeting as a core principle only budgets the cash you already have we run into a problem.

As you will have seen there is an experimental Report Budget option as an alternative but I have never used it. Maybe that is where your proposal would best fit for future development?

**Comment by youngcw** [comment]
I was thinking about this recently and had the same idea as here, to reuse the existing carryover structure that expense categories have and apply it to income categories.  I was thinking that we could reuse the existing carryover icons and tooltip setup as expenses.  Then the function could happen automatically in some way.  A simple, but not perfect, way would be to check the hold amount every time the budget is opened and update the hold automatically if needed.  Or this function could be handled the same way auto-posting of schedules is handled (whatever the specifics of that is).

**Comment by axelson** [comment]
> I wonder if it'd be possible to change the way income works so you can change which period it's -allocated- into, despite what period it was added to the register.

Yeah this is exactly how I picture this working. For each income transaction you could control if it's available for the current month or for next month. I don't know the details of Actual's data model but I could definitely picture it being quite tricky to implement!

This is one of the features that I miss from YNAB4.

I can live without it but it does necessitate updating the hold amount twice a month or so when I get paid since I like to keep my "to budget" amount at 0.

**Comment by erikhuizinga** [comment]
I also would very much like an option to allocate all income's time of availability, e.g. next month. My reasoning (as a newcomer to actual but a veteran to YNAB-style budgeting:
- Months are a standard time period, though that's only by convention and nothing 'natural' dictates that one should use months. (Think about it: they're almost always 28, 29, 30 or 31 days long. Crazy, right?) In that sense I get the decision to make income available to you as soon as it arrives. But why then have months in the budget in the first place, and features like rollover? So yes, you can also timebox income, as another convention.
- Given the aforementioned arbitrary time periods: budgeting to zero is a powerful peace-of-mind strategy within such periods. Then suddenly some income arrives, expected or not, and there goes your zero budget for the rest of the month. No, I don't like having to reallocate this money in the current month, because (see previous point) the month is a completely arbitrary unit of a time period and for all we know, the income might arrive 1 second before the next month starts, leaving me no time to even enter it in Actual, let alone allocate it to some place that I will spend money from. I know, I know, this money then rolls over, but that's not the point. The point is that the budget is no longer at zero because of date coupling (a code smell, if talking about software design principles). Let expenses be real-time (because you pay what you must pay), and let income incorporate a potential time buffer (e.g. a month or a few ahead) (because you shouldn't allocate to spend today what you might need in the future). Holding all income to some future time period by default preserves the current month's zero budget: budgeting bliss!
- Allowing a time buffer for income, reduces your dependency on that income: financial sanity!

I know that it's also possible, e.g. with templates, to sink all income into a category, and then consume from that in the next month's budget, but that's just obfuscating the problem that this issue has no solution, AFAIK.

**Comment by lazynooblet** [comment]
I will use this feature, thank you, I appreciate the effort. It is definitely an upgrade.

I do however feel like it has been over-engineered. A simpler approach would have been a new category called "Hold for next month" and allow the user to assign new income to that category. Now I need to all or nothing, which isn't as flexible.

Perhaps the entire hold mechanic prevents such a simple solution.

**Comment by RedHare-Exe** [comment]
@lazynooblet You can do what you're describing. Just create a new income category manually, set it to hold, and then assign income you want to hold to that category. If there's income you don't want to hold, assign it to the default "income" category.

**Comment by lazynooblet** [comment]
> [@lazynooblet](https://github.com/lazynooblet) You can do what you're describing. Just create a new income category manually, set it to hold, and then assign income you want to hold to that category. If there's income you don't want to hold, assign it to the default "income" category.

I just tried this and it works. Thank you! I misunderstood the feature obviously.
