### ISSUE TITLE
[Bug]: Transfer category between Off Budget and Budget

### ISSUE THREAD

**Issue by pogora** [actualbudget/actual#1979]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue

### What happened?

When transferring money between Budget accounts the category is automatically set to _Transfer_.
Transferring money from an Non-Budget account (i.e. Savings, Daily Savings) to a Budget account (i.e. Checking) does not set any category and warns that there are "x uncategorized transactions".

I could not find any mention of this in the help. Furthermore adding a category for this seem counterproductive since it would show up in the budget report.

![2023-11-26 22_24_18-ActualBudget - Actual](https://github.com/actualbudget/actual/assets/35605240/19f309d7-2002-4abf-8b21-e4a4eb1e88bc)

### Where are you hosting Actual?

Docker

### Operating System

None

**Comment by kymckay** [comment]
Hey there, this is expected behaviour. Money which is moving in or out of your budget pool needs to be attributed to a category (this is the same principal as regular transactions in / out of your budget).

But perhaps this is signal that it's something which needs to be more clear in the documentation.

**Comment by pogora** [comment]
Yes. It would be good if the documentation mentioned this preferably here:
https://actualbudget.org/docs/transactions/transfers

Although today I found a mention here at the bottom:
https://actualbudget.org/docs/budgeting/categories
