### ISSUE TITLE
[Bug]: Wrong amount budgeted for category with multiple schedule goal templates

### ISSUE THREAD

**Issue by pyfisch** [actualbudget/actual#1983]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue

### What happened?

I create 3 monthly schedules which total 327.11.
![image](https://github.com/actualbudget/actual/assets/2781017/f815c2ff-8d76-42f5-ad5d-8903ffaeb3c9)

Then I add them as goal templates to the category "Bills":

```
#template schedule Rent
#template schedule Electricity
#template schedule Mobile
```

Finally I apply the budget template for December and expect that 327.11 is budgeted. However triple that (981.33) is budgeted.

![image](https://github.com/actualbudget/actual/assets/2781017/b63ccac5-6dd9-4f9f-adf2-318eb63db20a)

It appears that if X schedule goal templates are added to a category the budgeted amount for each schedule is added X times to the category.

Sample database to reproduce the bug: [schedules-goals.zip](https://github.com/actualbudget/actual/files/13480319/schedules-goals.zip)

cc @shall0pass you've done a lot of work in this area

### Where are you hosting Actual?

Docker

### What browsers are you seeing the problem on?

Firefox

### Operating System

None

**Comment by shall0pass** [comment]
I'll call that a WHOOPS on my behalf.  Please check the linked PR #1984 to verify it's fixed.  Sorry about that.

**Comment by Kidglove57** [comment]
@shall0pass This fix was working for me at the end of November but the new month has thrown up a problem (for me at least). This has come to light because my categories are now full (less any transactions on the 1st).
So in the example given above:
#template schedule Rent  (say 1000)
#template schedule Electricity (say 100)
#template schedule Mobile (say 50)

So total budget for Dec 1150 less paid 1000 = 150 still available in December. 
This is what is happening in January:
1) Say I have paid the Rent for December but nothing else
2) I now try and fill the category for January using the above Goal Templates
3) BUT only 1000 is going into the category for January ie topping it up to 1150 but not treating January as a discrete month with a fill of its own of 1150

**Comment by shall0pass** [comment]
@Kidglove57 Here is the WIP method I mentioned above.

https://github.com/actualbudget/actual/pull/2001

**Comment by Kidglove57** [comment]
Thanks for explaining  @shall0pass. I think what’s bothering me is that this is then out of line with how a single line template behaves. Say; “#template 100” which will fund 100 regardless of any brought forward amount.

I am using the multiple schedule template in a monthly subs category and in a household bills category. Where the scheduled payments are the same each month. The solution is of course for me to hold off funding the next month until the turn of the month. Not a big deal but I just found it confusing compared to my single line template. The multi line schedule template now seemed to behave more like an “up to” template.

I’ll certainly take a look at the other link you mentioned. Thanks for your hard work on this!

**Comment by youngcw** [comment]
@Kidglove57 the Schedule template is best compared to the "by repeat" template.

@shall0pass Here is a crazy idea.  What if the schedule template processing converted the schedule into a "by" template and then ran that instead of having custom processing?  Do "by" templates handle what Paul is seeing better?

**Comment by shall0pass** [comment]
@youngcw Converting the schedules to 'by repeat' could also be difficult.  Some schedules can have multiple days per month per schedule.

@Kidglove57 Maybe an option is to use the 'full' keyword for monthly schedules.  'full' forces the whole schedule to be budgeting in the month of the schedule, so for monthly schedules it might be a more desired output.  If that works better, it could be applied on all monthly schedules that don't need a '$/number of months' calculation.

**Comment by Kidglove57** [comment]
@shall0pass thanks for the tip, I’m out this evening but I will certainly try that tomorrow. So that would be multiple lines for my monthly bills in the format:
#template schedule full {SCHEDULE NAME}  ?

**Comment by Kidglove57** [comment]
@shall0pass 
#template schedule full {SCHEDULE NAME} ?

I found a few moments before I went out.
 #template schedule full {SCHEDULE NAME} 
Works perfectly for my multiple line monthly scheduled bills!

Thank you so much

**Comment by shall0pass** [comment]
What are your thoughts on making that the default behavior for schedules with an 'every 1 month' cadence?

**Comment by youngcw** [comment]
> What are your thoughts on making that the default behavior for schedules with an 'every 1 month' cadence?

For exactly 1 month cadence that probably would make sense. Its not that different, but probably would match what people expect more often than not.

**Comment by Kidglove57** [comment]
> What are your thoughts on making that the default behavior for schedules with an 'every 1 month' cadence?

I’m also fine with this so long as we can document it fully for the casual user. Thank you!

**Comment by shall0pass** [comment]
I'll put something together so it can be tested. Unless someone beats me to it :)
