### ISSUE TITLE
[Feature] Allow transfers to have categories

### ISSUE THREAD

**Issue by SierraKomodo** [actualbudget/actual#1997]
### Verified feature request does not already exist?

- [X] I have searched and found no existing issue

### 💻

- [X] Would you like to implement this feature?

### Pitch: what problem are you trying to solve?

I'm setting up a budget using the 50/30/20 system and, as part of that, I'd like to track and budget credit payments while also being able to track and budget expenses on the credit cards themselves.

At the moment, the only thing hindering this goal with Actual is an inability to set budget categories on transfers, and these transfers not appearing in the budget panel as a result.

### Describe your ideal solution to this problem

Allowing categories as an optional entry for transfers between budget accounts would solve this.

**Comment by qmph22** [comment]
This would be helpful to budget for transactions where both the accounts are created in Actual. Paying my credit card or having a loan comes to mind.

For example, I could be transferring money from a checking account to a savings account and while it's technically being accounted for, I can't make a budget for it which means I can't track it as easily as a purchase. A workaround could be to create a payee and track transactions to the payee which isn't ideal. The inability to categorize transfers can incentivize me to not create all of my accounts within Actual because I won't be able to correctly budget my transfers.

**Comment by Kidglove57** [comment]
I am trying to understand how this would work with the default envelope budgeting system in Actual? To try to explain my thinking:
1) An envelope budget does not care what account the money is in because it is focussed instead on the purpose of each spending transaction within the budget (i.e its spending category).
2) So a transfer between on budget accounts does not change the way my net “for budget” funds are allocated and is therefore not categorised. In other words, the allocation to groceries, utilities, savings and so on is done at a high level in terms of giving a job to all available funds and not at the individual account level.
3) Of course if longer term debt is being gradually paid off it would make sense to have that debt “off budget”so that the transfers out, to pay it down, are categorised and are part of the monthly budget planning.
To the best of my knowledge all Envelope Budgeting systems work this way.

I hope this makes sense? I’m not familiar with how it all works in the experimental Reporting Budget though.

**Comment by qmph22** [comment]
@Kidglove57 I can definitely see what you're saying there. I took all of my larger debts and savings accounts and made those off-budget accounts. When I'm transferring money to these accounts, they can correctly be categorized. 

Perhaps in the case of this feature request, a tag would work better? If we're looking at all of our accounts at a high level, is there a mechanism within Actual to see cash flow within an account to avoid running negative in a checking account (for example)?

**Comment by Kidglove57** [comment]
I do agree with you about tags! At the moment I just put an "#tag" in the Notes box and use the filter tool to find all transactions with that particular "tag" in a particular date range. But I agree that what I am doing is just a work around.

As regards ensuring an account does not go overdrawn. I have the running balance enabled for every account, so I can at least see the impact of my scheduled transactions over the next week and move money back the my account if it is needed. I would love to be able to see further out though. Maybe someone would know how to design a forecast balance report? I guess it could only work with whatever schedules are set up though?

**Comment by savionlee** [comment]
So should I put my savings account into off budget? I'm trying to show my net-savings. I will make a transfer to hold half of my mid month paycheck for future expenses like rent.

My accounts look like

On budget
> Checking
> Savings

Transactions 
> Note       | account  | debit | credit
> half rent  | checking |  0  | 500
> half rent  | savings  | 500 | 0
> save money | checking |  0  | 200
> save money | savings  | 200 | 0
> pay rent   | savings  |  0  | 500
> pay rent   | checking | 500 | 0
> Apt pmt    | checking |  0  | 1000


So I'd like to show in my budget that I saved a net $200.

**Comment by CrazyKidJack** [comment]
@Kidglove57 

I don't really understand why transfers _**shouldn't**_ have categories. I can understand for some, they may not find it useful... but other may find it useful and...

If both accounts are on-budget... then they always offset and it's not a big deal from a budgeting perspective (it wouldn't conflict with the envelope budgeting system because you wouldn't ever need to allocate dollars for it). Additionally, I think saying "envelope budgeting system doesn't care about x" is a moot point. **_People_** care about where their money is. People **_use_** envelope budgeting systems. If there is a feature that doesn't mess with the budgeting aspects of AB, **_but also_** allows people to better manage other things they care about... that seems like a win. And if the argument is "well we only care about features that deal with envelope budgeting"... then why does AB support off-budget accounts at all?

If one account is off-budget then no change is required... AB already supports categorization in this case.

**Comment by Kidglove57** [comment]
@CrazyKidJack are you able to give an example of how both sides of an on budget transfer might be categorised please? Just so I can understand better. Is it just to ensure that the money in "x" account reconciles to the balance in say the "Savings" or "Vacation" category?

I don't know of any envelope budgeting system (I have tried about 6) that allows on budget transfers to be categorised. But I am open to hearing how it might work.

**Comment by savionlee** [comment]
> So should I put my savings account into off budget? I'm trying to show my net-savings. I use my savings account as a holding tank for known future expense. I will make a transfer to hold half of my mid month paycheck for future expenses like rent.
> 
> My accounts look like
> 
> On budget
> > Checking
> > Savings
> 
> Transactions 
> ```
> Note       | account  | debit | credit
> half rent  | checking |  0  | 500
> half rent  | savings  | 500 | 0
> save money | checking |  0  | 200
> save money | savings  | 200 | 0
> pay rent   | savings  |  0  | 500
> pay rent   | checking | 500 | 0
> Apt pmt    | checking |  0  | 1000
> 
> ```
> 
> 
> So I'd like to show in my budget that I saved a net $200.

@Kidglove57  my journal here seems like a good example for this. So far, I only see that I would need another IRL bank account to separate out what is savings and in AB add that as off balance. Can it be done with one bank account?

**Comment by Kidglove57** [comment]
If there is just one bank account, then I think the savings need to be on budget and let the Savings category take care of the numbers. I take it you are the default envelope budget?

To explain my real life thinking. 

I have savings accounts that are both off budget (long term objectives) and on budget (contingencies/no defined purpose). I have budgeted for 20 years or so without categorising "on budget" transfers. I do of course have to categorise transfers to and from off budget accounts.

As an example,"on budget" I might have fictional categories that look like this in terms of available funds:
Holidays 10,000
Contingencies 2000
Annual Bills 1500
Savings (short term objectives) 5000

It would be a bit of a nightmare having a separate bank account for each of these. So the category balances become like proxy accounts. I can now stand back and look at when money is needed and decide how much to keep immediately available and how much to put on easy access/short notice accounts to earn interest. The balances on each account do not need to relate directly to the category balances SO LONG AS the total of on budget accounts equals the amounts available in all my budget categories. This is why I have been quite happy never to categorise on budget transfers. 

Sorry to say a lot you may already know - this is just to give context.

**Comment by CrazyKidJack** [comment]
> @CrazyKidJack are you able to give an example of how both sides of an on budget transfer might be categorised please? Just so I can understand better. Is it just to ensure that the money in "x" account reconciles to the balance in say the "Savings" or "Vacation" category?
> 
> I don't know of any envelope budgeting system (I have tried about 6) that allows on budget transfers to be categorised. But I am open to hearing how it might work.

### If you are just asking about how it would work technically:
there will be a transaction record from acct 1 to acct 2 (maybe 2 records depending on how actual stores transfers). From my understanding, every transaction record has a field for a category (even off-budget ones have this I think... it just isn't shown). So all the user has to do is select the category and that value will be saved in the category field for that transaction in the DB record(s). If transfers are stored as a single DB record, ezpz. If they are stored as two DB records, then AB just needs to give that same category to both DB records.

### If you are asking how or why people would use it:
I can think of at least one way, but I'm just one person. Perhaps a better person to ask would be the OP of the feature request. In fact, the OP and qmph22 already mentioned 1 or two cases they would like to use it for. The one way I would think of is, for example, if I have an account I own and an account my partner owns in AB, when I pay for something (for which the transaction has a category) that my partner owes me for, when they pay me back, I could categorize the transfer against the category(-ies) that the original transactions were for. I know this can be handled in several ways, but you just asked for an example of how it might be used. Seems like now we have at least 2 or 3 such examples in this thread.

### Philosophy
I generally don't like when software restricts use-cases that are technically possible but artificially limited. In understand that sometimes such restrictions are required to ensure consistent and intuitive functioning of the application and/or to reduce maintenance costs. However, in this case, allowing categories for transfers wouldn't disrupt Actual's existing functionality or increase maintenance effort. It would provide value to those who want it, without affecting those who don't.

If you wouldn't use it or aren't sure how you would use it, that's fine, but why limit others? Removing the restriction wouldn't change how Actual works for anyone who doesn’t use the feature, while benefiting those who do. Restricting it seems like unnecessary work for developers - it's simpler to allow people to categorize transfers as they wish. Instead of anticipating all potential valid use cases and restricting anything not anticipated, it’s easier to focus on anticipating and limiting only known-problematic cases. Why not reduce complexity by removing this artificial limitation?

**Comment by Kidglove57** [comment]
So in effect this would pick the money out of one category (one side of the transfer) and put it into another (the other side of the transfer?) Giving an audit trail that does not exist under the current methodology?

I guess at the end of the day it comes down to someone with the required coding experience being ready to pick this up and run with it. I don’t know whether the moderators have a particular view on this issue.

**Comment by CrazyKidJack** [comment]
@Kidglove57 

> So in effect this would pick the money out of one category (one side of the transfer) and put it into another (the other side of the transfer?)

No I don't think that is correct. I think both sides of the transfer would have the same category, so they would always cancel out (payment in category x on one side of the transfer and deposit in category x on the other side of the transfer).

**Comment by Kidglove57** [comment]
I agree they may well be the same category but equally  I can envisage situations in which they just might be different ....

**Comment by savionlee** [comment]
I use a tracking budget. How would this work there?

**Comment by Teprifer** [comment]
> So in effect this would pick the money out of one category (one side of the transfer) and put it into another (the other side of the transfer?) Giving an audit trail that does not exist under the current methodology?
> 
> I guess at the end of the day it comes down to someone with the required coding experience being ready to pick this up and run with it. I don’t know whether the moderators have a particular view on this issue.

Just to clarify, money moves between categories is now tracked in the monthly notes since the last release with an update for it in the works.

**Comment by CrazyKidJack** [comment]
@Kidglove57 

Yeah I think it depends on how AB stores transfer transactions.
If it's a single DB record, then both sides of the transfer would have to match (because there is only one data element to represent the category for both sides of the transfer).

If AB stores them as two separate DB records, then yeah, I suppose each could have a separate category. Though, notably, when you create a transfer transaction, you would only be able to set one of those (because there is only one spot in the UI to set the category)... so I think it would make sense for AB to use that category for both DB records so by default they would match. Though, I do suppose there would not be anything stopping a user from going to the other account participating in the transfer and changing its category

**Comment by Kidglove57** [comment]
> there?

I'll leave that to others to answer - I'm not sure off hand 
how many use the tracking budget.

**Comment by Kidglove57** [comment]
> Just to clarify, money moves between categories is now tracked in the monthly notes since the last release with an update for it in the works.

Thanks for mentioning this. I did not know about this . I could not find this in the release notes but am probably scanning them to fast?

**Comment by Teprifer** [comment]
> > Just to clarify, money moves between categories is now tracked in the monthly notes since the last release with an update for it in the works.
> 
> Thanks for mentioning this. I did not know about this . I could not find this in the release notes but am probably scanning them to fast?

Ah looks like I was remembering incorrectly due to the timing, it was merged into edge right after the release so will be in the next one. 

The update PR is # #3411

**Comment by savionlee** [comment]
> > So should I put my savings account into off budget? I'm trying to show my net-savings. I use my savings account as a holding tank for known future expense. I will make a transfer to hold half of my mid month paycheck for future expenses like rent.
> > 
> > My accounts look like
> > 
> > On budget
> > > Checking
> > > Savings
> > 
> > Transactions 
> > ```
> > Note       | account  | debit | credit
> > half rent  | checking |  0  | 500
> > half rent  | savings  | 500 | 0
> > save money | checking |  0  | 200
> > save money | savings  | 200 | 0
> > pay rent   | savings  |  0  | 500
> > pay rent   | checking | 500 | 0
> > Apt pmt    | checking |  0  | 1000
> > 
> > ```
> > 
> > 
> > So I'd like to show in my budget that I saved a net $200.
> 
> @Kidglove57  my journal here seems like a good example for this. So far, I only see that I would need another IRL bank account to separate out what is savings and in AB add that as off balance. Can it be done with one bank account?

What I've ended up doing is not using the transfer option. instead I've setup payees so that I can categorize both sides of the transaction. This is my solution for the tracking budget.

So out of checking I categorize "savings" and in the savings account choose its specific category like "savings - auto". So I can budget both the total savings and which type of savings separately.

**Comment by db-src** [comment]
I second the request to allow optionally categorizing transfer transactions, at least on one side.

I'm looking to migrate from a system that doesn't support transfers except by categorizing them and making the notes match up.

Actual being able to physically link transactions that are two sides of the same coin is very appealing! Since without that I have to just make the reference/notes the same and compare that+amounts to identify matched pairs.

However, in my source system I always categorise the txn in the destination account as a "Transfer" and the txn in the source acct as Savings, CC Payments, etc. - This then grants an ability to quickly see on my budget (tracking style, but applicable to zero too afaik?) how much money has been allocated/moved for those purposes - and whether it mirrors the total of "Transfer", monthly trends, etc. - crucially, all of this _on the same page_ where I track spending and income amounts.

So it seems that to keep the same functionality I must forgo the very useful 'real' transfers in Actual, as if I use them, I'll be forced to discard years of category data. I don't really want to have to adopt a new workflow or view these flows on a separate report or whatever. I would just like the option to categorize the tfr on the source acct by e.g. Savings/CC/etc for budget tracking.
