### ISSUE TITLE
[Feature] Bring Back Account Types

### ISSUE THREAD

**Issue by YagiOoda** [actualbudget/actual#2021]
### Verified feature request does not already exist?

- [X] I have searched and found no existing issue

### 💻

- [ ] Would you like to implement this feature?

### Pitch: what problem are you trying to solve?

In the past, Actual allowed for account types. I propose to bring the account types back and be able to label each account with "Savings", "Investments", "Loan", etc.

### Describe your ideal solution to this problem

With custom reports, this would allow for treating transfers to different off-budget accounts differently. For example, right now when I pay my mortgage (a transfer from an On Budget account to an Off Budget account) that shows up in custom reports as a "transfer" and won't show up in expenses. Being able to type each account would allow treatment of accounts differently based on their type and show transfers to "Loan" accounts as expenses.

**Comment by YagiOoda** [comment]
I just wanted to put a link to @jfdoming's suggestion here: https://github.com/actualbudget/actual/issues/3025#issuecomment-2565979195

Supporting tagging in account notes would be a great addition and would allow for reports to get more granular. For example, my Traditional 401k account I'd want it to go under "investments" and "retirement" and maybe "tax-deferred" depending on the reporting.

**Comment by rodrigost23** [comment]
I would love to have at least credit cards visually separate to real accounts.

**Comment by matt-fidd** [comment]
In the meantime, using emojis to differentiate is a good stop-gap solution

<img width="36" alt="Image" src="https://github.com/user-attachments/assets/3713c735-be3a-408d-bdec-41d225185998" />

**Comment by juanpagg15ug** [comment]
I wanted to chime in on this because we faced this exact pain point—specifically with transfers to loans/investments being hidden or lumped together in Custom Reports—and found a clean way to solve it today without waiting for core schema changes.

### The Real Problem for Custom Reports
As @YagiOoda pointed out, the biggest limitation of having only On-Budget vs. Off-Budget is reporting. Emojis in account names look nice, but Custom Reports cannot filter or aggregate by emojis. 

However, **Custom Reports CAN filter by Notes / Tags** (e.g., `Notes contains #Loan` or `Notes contains #Retirement`).

### How We Implemented Account Subtyping & Reporting (Without Forking Core)
We use a small middleware script / ingestion service using `@actual-app/api` that treats account names as structured parameter holders and propagates that typing down to transactions:

1. **Standardized Account Metadata (`[Bank|Product|Currency|Number|Tag]`)**:
   Instead of just raw account names, we standardize accounts with bracket parameters:
   - `Mortgage Loan [Bank|Loan|USD|12345|#Loan #Mortgage]`
   - `Traditional 401k [Vanguard|Investment|USD|67890|#Investment #Retirement]`
   - `Daily Checking [Bank|Checking|USD|11223|#Checking]`

2. **Downstream Tag Propagation to Transactions**:
   Whenever transactions or transfers are created (via bank sync/API) or through a periodic post-processor script:
   - The engine extracts the account's product/tags (`#Loan`, `#Retirement`, etc.).
   - It appends these tags to the transaction's `notes` field.
   - For internal transfers, it appends both the source and destination account tags (e.g. `Transfer #Checking -> #Loan`).

3. **The Result in Custom Reports**:
   - Transfers to your loan or mortgage account automatically carry `#Loan`.
   - In Custom Reports, you can now build reports filtering for `Notes contains #Loan` (or `#Investment`), accurately isolating debt payments and investment contributions with zero manual tagging.

### Takeaway
While native account grouping (like PR #6921) will be a great UI improvement, the real functional bottleneck has always been **reporting granularity**. Propagating account-level classification tags down into transaction notes solves the reporting issue immediately while remaining 100% compliant with Actual's current database schema.
