### ISSUE TITLE
[Bug]: Your data is out of Sync

### ISSUE THREAD

**Issue by rich-howell** [actualbudget/actual#212]
### Verified issue does not already exist?

I have searched and found no existing issue

### What happened?

Syncronisation of my budget failed with an out of Sync message appearing again.

![image](https://user-images.githubusercontent.com/22135084/186707474-8af33364-f2e5-48ca-ad33-4eb88d26a40e.png)
![image](https://user-images.githubusercontent.com/22135084/186707499-7d34456b-a844-471f-9d05-1c16d8b0de1f.png)
![image](https://user-images.githubusercontent.com/22135084/186707519-b33e86a8-8b3f-4c40-ba67-7f73e55d7b73.png)

This is the budget on my desktop 
![image](https://user-images.githubusercontent.com/22135084/186707562-f32c2944-adee-4d55-bd8b-5c02fd83df20.png)

This is the more up to date budget, on my laptop 
![image](https://user-images.githubusercontent.com/22135084/186707604-ece3288b-0507-46c8-a4b7-b045bafa8a91.png)

Both say they are Synchronised.

### What error did you receive?

Your data is out of Sync.
There was a problem syncing your data. We can try to repair your sync state to fix it.

### Where are you hosting Actual?

Fly.io

### What browsers are you seeing the problem on?

Firefox, Microsoft Edge

### Operating System

Windows 11

**Comment by rich-howell** [comment]
Taken from Firefox 
![image](https://user-images.githubusercontent.com/22135084/186710927-36febdc2-8d07-446d-bad2-c4a0a33741f3.png)

**Comment by lancepick** [comment]
I experience the same issues as above, when I try to Import transactions via the API.

After the transactions have imported, if I refresh the browser the transactions appear to all be there, but shortly after I'll start seeing the Sync issue above.

My importer app is loaded in another docker instance that shares the Actual volume mount for the databases.

Where are you hosting Actual?
Unraid/Docker

What browsers are you seeing the problem on?
Chrome

Operating System
Windows 11 for the browser, Unraid for Actual Server

**Comment by chylex** [comment]
I'm also seeing this. Repairing doesn't work. Resetting sync also doesn't work, the message re-appears after I refresh the page.

![obrazek](https://user-images.githubusercontent.com/3685160/188382003-e5914f42-d657-4282-9162-0f6e29aaf7a1.png)

If I wipe the database from Firefox and download it again, the error appears **immediately** after the database is downloaded and I get a welcome dialog. I also lose all changes I made since this issue started happening.

All the logs say on the server is "Making backup".

**Comment by jlongster** [comment]
A lot of these bugs will be fixed by https://github.com/actualbudget/actual-server/pull/75

At the very least, resetting sync should absolutely be fixed in that PR (I discovered that it's currently broken while fixing that). The sync bugs are very likely fixed as well. Can't say for 100% sure because I don't know what caused the above, but overall syncing will be a lot more reliable

**Comment by rich-howell** [comment]
I pulled origin master from actual-budget and deployed to fly. Here is how it went

I took a backup of my data first. 
Pulled Origin Master 
Deployed to fly
Loaded my budget on a machine I was using it on successfully on before deploying
The Sync in the top right spins until it finally presents an error message 
I tried the reset sync from the settings which did nothing

I opened the budget on a new device, in edge in a private window and was presented with the message in the attached screenshot which I have no idea what it means.

![image](https://user-images.githubusercontent.com/22135084/190333460-0929c147-c512-4a9e-ad32-514710c87444.png)

I tried to open a new file to import my budget into and got this

![image](https://user-images.githubusercontent.com/22135084/190333513-7ffd57c7-d4cd-406d-a4e0-094dd6b8fc9b.png)

Error message comes up - sorry we couldn't sync you data, this is a bug and has been reported.

I pressed the revert button as per the docs https://actualbudget.com/docs/overview/syncing-across-devices/#debugging-sync-issues this makes teh syncing has been reset message go away but Syncing itself is not fixed.

![image](https://user-images.githubusercontent.com/22135084/190333553-935edb75-dfc6-46da-a272-5055f89587c4.png)
