### ISSUE TITLE
[Bug]: Syncting from GoCardless doesn't fill the Notes column

### ISSUE THREAD

**Issue by oleksandr** [actualbudget/actual#2133]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue

### What happened?

1. Link an account with GoCardless
2. Sync the transactions
3. Observe an empty column Notes
4. Tried it in the current file, reproduced in the new file from scratch.

### What error did you receive?

No error, just empty Notes column, which breaks some of my rules (I get Notes when import transactions from file).

### Where are you hosting Actual?

Docker

### What browsers are you seeing the problem on?

Firefox

### Operating System

Linux

**Comment by MatissJanis** [comment]
:wave: You'll want to check server logs for what information Gocardless gives for your bank. If there are no notes: you'll want to get in touch with Gocardless. However, if there are notes - you'll want to create a custom adapter for your bank so that the notes field is normalized to what Actual expects. This will need to be done by you or someone else who shares the same bank.

Information on how you can do that is available here: https://github.com/actualbudget/actual-server/blob/master/src/app-gocardless/README.md

We do not classify bank data discrepancies as a bug, so I'll close this off.

**Comment by oleksandr** [comment]
@MatissJanis thanks for the prompt reply. I've noticed that the right notes are coming in the `remittanceInformationStructured` field of the GoCardless response. I assume this is custom from bank to bank, will take a look into custom adapter.
