### ISSUE TITLE
[Feature] Add support for regionally differences

### ISSUE THREAD

**Issue by vinstaal0** [actualbudget/actual#2160]
### Verified feature request does not already exist?

- [X] I have searched and found no existing issue

### 💻

- [ ] Would you like to implement this feature?

### Pitch: what problem are you trying to solve?

Currently when you type in information it follows US standards, which you can only partly change for dates and for dots and comma's. Which means that if you are used to typing in figures and dates it will not work correctly. For me it can't find the dates (loads of countries use - as separator while the US uses the /) and it will not correctly note numbers like 1.234,56 typed in.separator

### Describe your ideal solution to this problem

The best solution would be to be able to check the settings on the input device/server. Another option is to make it so you can manually adjust it. (both would be even better)

### Teaching and learning

It would be a setting that will not do anything for Americans, but will be a godsend to the rest of the world

**Comment by Jackenmen** [comment]
Formatting options are available in Actual's Settings (available under More -> Settings):
![image](https://github.com/actualbudget/actual/assets/6032823/9c2d33c3-bacf-456d-9be6-8c3de85c4c23)

If a date or number format used in some country is missing, it can be added but your issue requests adding a new feature when the feature already exists.

**Comment by vinstaal0** [comment]
DD-MM-YYYY is missing and it doesn't work for the numbers you type in, I keep adding millions instead of thousands.
The feature exists, but is far from complete and I am also suggestion the automatic adaption.

**Comment by Jackenmen** [comment]
> DD-MM-YYYY is missing

Great, you can make a separate request for this and some contributor will likely resolve this part of your problem much quicker since it should be relatively easy to add another format. I'd suggest including the name of the country where this is considered standard too.

> it doesn't work for the numbers you type in, I keep adding millions instead of thousands.

It does work - it requires that you use the selected decimal separator instead of the default dot, i.e. I have "," selected as decimal separator and so I have to use "1000,00" to get a thousand instead of "1000.00" which gets transformed into "100 000,00" since "." is not the separator I have set. If you're experiencing a different behavior, perhaps there's a bug with this that haven't been reported yet, I can't reproduce it.

> I am also suggestion the automatic adaption.

If I understand correctly what you're asking for, this is already tracked in #894.

**Comment by vinstaal0** [comment]
I'll add another issue for the DD-MM-YYYY.

I just tested it again and it doesn't seem to work all the time for some reason. Next time I find out in what field it is ill create a bug report for it. Works in schedules though.

Issue #894 does suggest something that can help fix the issue, especially cause triple decimals aren't supported so maybe it can check that.

My suggestion is to just check what the user is using for locale and use that for display and input.
