### ISSUE TITLE
[Bug]: budget disappears after selecting "delete file locally"

### ISSUE THREAD

**Issue by lephtHanded** [actualbudget/actual#2216]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue

### What happened?

This happened yesterday on my work machine.
In an 'incognito browser' I'll log in, then download my budget after entering my password.  
I made all my changes, made sure the sync action is good then closed the budget and "delete it locally".
Usually when I do that, the budget is listed there "available to download"  but in this case it is gone completely.

The good news is that when I accessed the app from my home computer, everything was up to date including the changes I made from my work laptop.  I didn't need to restore any data.

### What error did you receive?

No error message, my budget simply wasn't listed.

### Where are you hosting Actual?

Docker

### What browsers are you seeing the problem on?

Chrome

### Operating System

Windows 10

### edit: spelling

**Comment by lephtHanded** [comment]
I tried deleting my cookies and that didn't help.

**Comment by ryan77627** [comment]
Yeah this actually confused me too. I'm new to the application, but I figured that pressing "Delete file locally" would remove any data of the file from my browser's local storage, and still list the file as some "remotely available" variant. Not only is the file "gone", but it won't show up on new devices I try to access it from as well.

Now I say "gone" because if you pull up the browser's network viewer and refresh the list of files, it does appear under the "list-user-files" endpoint as a *deleted* file, so it must have gotten marked as deleted (just like the delete from all devices button does...)
