### ISSUE TITLE
[Bug]: Changing account name does not work in 'Accounts' overview.

### ISSUE THREAD

**Issue by Flightkick** [actualbudget/actual#245]
### Verified issue does not already exist?

I have searched and found no existing issue

### What happened?

In the overview where all accounts are listed, I was not able to change the name of the account.

Steps to reproduce:

1. Go to `/accounts`
2. Click on the name field of an account and change its name
3. Press `Enter`
4. The account name is reset to the previous value

As a workaround, I was able to change the account name by going to the specific account view `/account/<uuid>` and clicking the account name header.

Using Docker `jlongster/actual-server:1.0.3-alpine` `linux/amd64`

### What error did you receive?

No error messages were shown
The value does not get committed, no sync request is made.
The field in the user interface silently resets to its previous value.

### Where are you hosting Actual?

Docker

### What browsers are you seeing the problem on?

Firefox, Chrome

### Operating System

Windows 10

**Comment by TomAFrench** [comment]
Could you provide some screenshots to show where you're clicking on step 2?

I can't see anything similar except this field in the transaction table. This is for attaching the transaction to a different account rather than renaming an account however.
![image](https://user-images.githubusercontent.com/15848336/188632039-6813a721-e2a5-475c-ace4-852492771ef0.png)

**Comment by Flightkick** [comment]
Ah I see, you're right. I misunderstood what that field was for.
Now that I don't start typing immediately I see the 'For budget' label as well.
