### ISSUE TITLE
Actual in the browser: can't choose payee

### ISSUE THREAD

**Issue by MiriamNZ** [actualbudget/actual#274]
You enter the field, the dropdown appears, but when you choose an item by touching it, it does not select. 
Instead your insertion point has moved to the line underneath the drop down menu. 

Makes the website app unusable. 

If anyone knows an alternative way of selecting from the dropdown menu without touching on the iPad screen please comment!

Safari. OS 15.2. IPad.

**Comment by rich-howell** [comment]
Hey @MiriamNZ 

We are working on a responsive version of Actual web right now, I am going to go ahead and close this issue off for now if the issue persists once we have merged the responsive version down please do feel free to open this issue back up.

Cheers
Rich

**Comment by albertogasparin** [comment]
The responsive version has been merged but it is read-only and this issue still persists. Also, the default viewport on iPad is perfect for Actual, so I think better supporting touch input should be different from adapting the layout to work on smaller screens.
Given how annoying this issue is, happy to support/contribute to the development if we agree this should land sooner than a fully fledged mobile version.
