### ISSUE TITLE
[Feature] Option to create a new category when adding a transaction if a category doesn't exist

### ISSUE THREAD

**Issue by Tigatok** [actualbudget/actual#2787]
### Verified feature request does not already exist?

- [X] I have searched and found no existing issue

### 💻

- [X] Would you like to implement this feature?

### Pitch: what problem are you trying to solve?

When adding a transaction, if the category doesn't exist, you have to manually go create the category and then come back and update/add your transaction.

### Describe your ideal solution to this problem

We should allow the option to create a category similar to how we can create a payee when one does not exist. UI TBD. We could also extend this functionality to an import (Create a category if one does not exist? -- Option could be added)

### Teaching and learning

It should be pretty clean when a user goes to create a new transaction.

**Comment by gitchap** [comment]
Similar request: #4240

**Comment by aalkz** [comment]
This would be a very welcome feature for people coming from YNAB that expect and are used to this behavior already.

When you're adding a transaction, having to switch to the Budget section to add it and then go back to categorize it is a bit cumbersome, especially for new users that don't have all their categories thought out yet. Also, if you're new to Actual and start by adding an account and begin registering transactions, you don't really know that you have to go to the Budget section to do that, so you just see "Categorize" and a red "1 uncategorized transaction" text at the top, and even if you click that you can't add categories because it's just a list of the uncategorized transactions. You have to go to Budget, then hover over a group to see the "+" or create a new group, add category and then go back to categorize. All this back and forth is a bit confusing.
