### ISSUE TITLE
[Feature] Progress bar for targets/templates

### ISSUE THREAD

**Issue by jacmei** [actualbudget/actual#2965]
### Verified feature request does not already exist?

- [X] I have searched and found no existing issue

### 💻

- [ ] Would you like to implement this feature?

### Pitch: what problem are you trying to solve?

Like how YNAB would display a visual indicator for how far along you are until meeting your target, I would love Actual Budget to implement a similar feature.

![image](https://github.com/actualbudget/actual/assets/39633460/cc384004-dda6-4192-a40c-3f65ff8db963)

### Describe your ideal solution to this problem

I understand that templates are in the works right now so this should be tackled afterwards. It should be displayed right under each category.

**Comment by ebkalderon** [comment]
Sorry to necro this old ticket, but was this feature actually implemented and completed, as per the issue's current status? I can't see any way to enable this in the demo.actualbudget.org instance.

**Comment by youngcw** [comment]
> Sorry to necro this old ticket, but was this feature actually implemented and completed, as per the issue's current status? I can't see any way to enable this in the [demo.actualbudget.org](https://demo.actualbudget.org/) instance.

This feature request is still open

**Comment by ebkalderon** [comment]
Thanks for the clarification! Apologies again for necro-ing the thread. I wish I was more confident in my JS/TS skills, or I would contribute directly myself.

**Comment by tbuist** [comment]
I've completed a prototype to show progress bars for categories and templates/goals. I will try to open a PR for this.

![Image](https://github.com/user-attachments/assets/f42359f8-bebb-4098-b343-4b4ef7226615)

**Comment by tostasmistas** [comment]
@tbuist - Similar to what YNAB has, do you think it's possible to have the progress bars be optional? I for instance, sometimes liked to have them turned off to be easier to glance at what categories I have and how they are organized.

<kbd><img width="577" alt="Image" src="https://github.com/user-attachments/assets/186cc18e-3d29-4bcd-9df0-052cc12bb187" /></kbd>

**Comment by tbuist** [comment]
Good idea, I've added a configuration option to the Settings->Theme section.

![Image](https://github.com/user-attachments/assets/2af87019-6580-4b98-bb13-04b939c0e57a)

**Comment by ohnefrust** [comment]
Hey guys - I'm new to this so excuse me if I'm missing any important points while contributiing. I've vibe coded a simple solution but not for targets yet as they are not available in the UI:

<img width="1514" height="1000" alt="Image" src="https://github.com/user-attachments/assets/859a5d7a-138b-447d-8a0a-c2ec35aa150d" />

Maybe this could be a simple solution to start this whole progress bar topic? I decided to go with a very simple approach: The bar simple compares spent to budgeted. There are the following options:

1. If there's a budgeted amount (or none at all) and nothing spent, then there's no bar.
2. If there's a budgeted amount and spendings are below or equal to the budgeted amount, the bar is green and represents the percentage spent from left to right
3. If the spent amount is larger than what's budgeted, the bar turns red and any overspent amount is represented in a darker red, relative to the amount that was budgeted.
4. The bars can be toggled on or off in the top right corner. On top of that, it can be toggled on / off in experimental features.

As soon as targets are available in the UI, I think the feature could be adjusted to represent the more complex logic similar to YNAB.

Coming from YNAB, the visual bar is one of the features I miss the most, that's why I decided to give it a try with Claude Code ;)

**Comment by ohnefrust** [comment]
I went one step further and combined it with a simple UI for templates:

<img width="779" height="958" alt="Image" src="https://github.com/user-attachments/assets/43d194c2-2c29-42e7-a759-830afbe728bf" />

**Comment by whisperKnight887** [comment]
@ohnefrust 
I just came across this discussion and noticed your branch and It looks really useful! 
Are you considering opening a PR for it? 
Thank you for your effort on this feature!
(P.s English is not my language, sorry if I make mistakes)

**Comment by RadicalRadish200** [comment]
Thanks for putting this together @ohnefrust, it looks really good. Would you consider opening a PR to Actual for it? I think it could be useful for a lot of us here. Sorry in advance, I’m very new to GitHub and not sure how these things usually work. - Radish

**Comment by ohnefrust** [comment]
@RadicalRadish200 @TacticalPidgeon9941 thanks for the feedback. I've opened the PR. I know I'm mixing two things here (progress bar AND target template UI) but I cannot think of progress bar without thinking of templates.

**Comment by aaryan-rampal** [comment]
Lovely product by the way. I am really pro-progress bars ever since I tried out Monarch Money a while back. YNAB is good, but I remember Monarch also had a cool feature where it showed a vertical separator on the progress bar which related to the current day of the month (averaged spending per day). Very small but very neat QOL, instead of trying to keep under budget and mentally doing math, you just try to match that vertical line. Slow down a bit when your spending goes over. It adds more value to the progress bar. 

  I looked through the previous attempts/discussion in #3424, #4371, and #7276. My read is that the hard part was the progress bar carrying too many meanings at once: budget/spending state, rollover, goal/template progress, underfunding, and target UI.

  I’d like to propose a (very) narrow version that is only per-month budget usage, not goal/template progress.

  For each visible budget month/category cell:

  `base` = rollover from previous month + budgeted this month
  `spent` = spending in this category for this month

  Display rules:
```python
if base > 0:
    if spent < base:
        partial green bar, width = spent / base
    elif spent == base:
        full green bar
    elif spent > base:
        full red bar
elif base == 0:
    if spent == 0:
        full green bar
    elif spent > 0:
        full red bar
elif base < 0:
    full red bar
```

The bar would mean only:

  > How much of this month’s available category money has been consumed?


  I think this addresses one of the issues raised in #4371, where a category could appear “bad” because spending exceeded the amount budgeted this month, even though the category still had money available from prior-month rollover. I like the rollover functionality of Actual. It gives the user more freedom with re-allocating funds. We should do the same for progress bars. No need to hand-hold the user, they know what they are doing with carryover, the progress bar is just meant to complement their existing relationship with Actual.

  It also avoids the broader scope of #7276 by not adding template editing, template columns, backend template preview actions, or target UI. 

  We could then easily add some sort of vertical line. Nothing fancy for now, but maybe later we could assign green to under budget and a gradient from yellow to red to show a 'danger zone' i.e. overspending relative to averaged spending for the day of the month. 

  Would this narrower per-month interpretation be acceptable as a focused PR?
