### ISSUE TITLE
[Feature] Default account and "cleared" value when adding new transaction

### ISSUE THREAD

**Issue by TailyFair** [actualbudget/actual#3067]
### Verified feature request does not already exist?

- [X] I have searched and found no existing issue

### 💻

- [ ] Would you like to implement this feature?

### Pitch: what problem are you trying to solve?

Most of the time I use one and only account when entering transactions and almost always transactions are already cleared.
So it becomes tedious to always do these steps and I would love to add transactions faster and more efficiently.

### Describe your ideal solution to this problem

I would like to either:
a) Allow to customize defaults - default account and default "cleared" values
b) Always fill previous transaction values for account and "cleared" value

### Teaching and learning

Maybe add settings modal in transactions page where you can set this up?

**Comment by atgrey24** [comment]
I believe a more accurate user story would be:

As a Mobile user, I want the New Transaction interface to automatically populate the "Account" field, so that I can reduce the number of button clicks and speed up transaction entry on the go.

The "Account" population rules could be one of the following options:
1. A "favorite" or "default" account, chosen by the user
2. The most frequently used account, as determined by transaction history
3. The most recently used account, selection remembered from previously entered transaction (persistent across sessions)

I'm less on board with the "Cleared" behavior. It mainly seems useful for entering actual Cash transactions (e.g. you have an "account" tracking the cash in your wallet), where there is never a delay between when the transaction occurs and when it "clears". Perhaps "automatically clear transaction on entry" could be an Account setting? For example, this seems to be the only difference between Checking and Cash account types in YNAB

**Comment by TailyFair** [comment]
Seems like this issue can be solved by just using rules, as described here
https://actualbudget.org/docs/budgeting/rules/custom/#q-how-do-i-set-a-default-account-when-i-add-transactions

Just on mobile, it seems to be bugged setting Cleared value. Registered bug: https://github.com/actualbudget/actual/issues/3071
