### ISSUE TITLE
[Bug]: Can't add MBANK_RETAIL_BREXPLPW using GoCardless integration

### ISSUE THREAD

**Issue by mwojtaszewski** [actualbudget/actual#3157]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue
- [X] I will be providing steps how to reproduce the bug (in most cases this will also mean uploading a demo budget file)

### What happened?

I tried to add bank account from `MBANK_RETAIL_BREXPLPW` but every time I get  "An error occurred while linking your account, sorry!"

Steps to reproduce:
![image](https://github.com/user-attachments/assets/432c4815-b8f9-4512-882e-a8877b7d8d7a)

Looking at the backend logs, there is a problem with request to `/api/v2/agreements/enduser/`, which always return 400 Bad Request. 
I can add accounts from other institutions without any problems.
I'm using the latest version of Actual, v24.7.0

### Where are you hosting Actual?

Docker

### What browsers are you seeing the problem on?

Chrome

### Operating System

Windows 11

**Comment by vrozaksen** [comment]
Same here!
Logs: https://gist.github.com/vrozaksen/a2532254e39ab821dbe1d54ed7dbc1a6

**Comment by MatissJanis** [comment]
👋 Can you please link me to the Discord conversation about this error?

Thanks

**Comment by vrozaksen** [comment]
> 👋 Can you please link me to the Discord conversation about this error?
> 
> Thanks

I started it here:
https://discord.com/channels/937901803608096828/1267500771814150276

**Comment by MatissJanis** [comment]
Perfect. The community will be able to assist better on Discord with debugging this issue. If they deem it to be a real bug in actual - then we can open up an issue.

Why this way? Because we have a lot of people actively assisting with tech support on Discord. Whereas on github we mostly have the maintainers who are very limited in their capacity to offer tech support.

<img width="954" alt="Screenshot 2024-07-28 at 20 36 26" src="https://github.com/user-attachments/assets/8738005e-bcff-473c-b333-67fd9ca33fbb">
