### ISSUE TITLE
Amounts are cut off in Account page

### ISSUE THREAD

**Issue by kazzazed** [actualbudget/actual#327]
Debit, Credit and RT amounts over $x,xxx.xx are cut-off in account view. I'm using a 21.5" monitor so plenty of screen real estate. Only way I can read the full amount is to click into the amount field and use the arrow key, or copy/paste it out to notepad.
Ideally the columns in Account view should be dynamically adjustable through drag and depending on screen size. Sorting by column click would also be useful, but these last 2 are more feature requests. Not being able to read the amounts is more of an issue.

**Comment by j-f1** [comment]
One way we could fix this is by adding a setting to drop the decimal points from displayed currencies. I imagine people dealing with 6-7 figure currency amounts on a regular basis won’t care about the fractional units, so that buys us up to X,XXX,XXX:
<img width="128" alt="Screenshot_2023-01-30 18 04 23" src="https://user-images.githubusercontent.com/25517624/215616578-ec440547-5319-433e-867f-2fd8f0b4d404.png">

Maybe the option could be expanded to additionally replace the last 000 with `k`? so then big numbers would render as e.g. 1,400k instead of 1,400,000.

**Comment by j-f1** [comment]
I’ve opened #725 which makes some improvements here. I’d love it if some of you would be willing to import a backup to the test instance at https://deploy-preview-725--actualbudget.netlify.app/ (as long as you click “don’t use a server” you won’t be sending any data outside of your browser). Once you go to More → Settings → Number format and toggle on “Hide decimal places,” you should get the new behavior.

**Comment by MatissJanis** [comment]
👋 I believe Jed has done some great work to improve the situation here in #725

Closing it off, but please feel free to open a new issue if you would like to collaborate on doing further improvements in this area.
