### ISSUE TITLE
[Bug]: Suggested Payees is inconsistent

### ISSUE THREAD

**Issue by psybers** [actualbudget/actual#3316]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue
- [X] I will be providing steps how to reproduce the bug (in most cases this will also mean uploading a demo budget file)

### What happened?

If you view the suggested payees, after favoriting two, you might see something like this:

<img width="357" alt="image" src="https://github.com/user-attachments/assets/039037ca-070e-4db8-8ef9-8038b5e136ac">

But if you then go to add a new transaction, the payee list looks like this:

<img width="384" alt="image" src="https://github.com/user-attachments/assets/b0648b1c-6eb0-434c-8be9-671529c3b8d2">

It seems to forget to show the favorites.

### Where are you hosting Actual?

Docker

### What browsers are you seeing the problem on?

Chrome

### Operating System

Mac OSX

**Comment by qedi-r** [comment]
This seems to be limited to the case where you are selecting the payee without an account selected. Investigating what is different in this path.

**Comment by psybers** [comment]
> Ah, I guess it's time to fix this then: [#2814 (comment)](https://github.com/actualbudget/actual/pull/2814#issuecomment-2170543501)

I'm not entirely sure the two are related, but maybe.  Either way I guess we can try to fix that here.

**Comment by qedi-r** [comment]
My assumption here is that not displaying any payees when an account is not yet selected on new transactions is the bug as shown below: 

![image](https://github.com/user-attachments/assets/70220211-3003-41a1-bc9e-58580d308217)

if this is fixed, then the missing favorites is also fixed. The fix is the payees.filter line 1243 on TransactionTable.tsx.

If this is intended to not display payees, then we need to know when this is the case, and not add common payees to this list.
