### ISSUE TITLE
[Bug]: Scheduled transaction preview with splits shows split error 

### ISSUE THREAD

**Issue by joel-jeremy** [actualbudget/actual#3353]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue
- [X] I will be providing steps how to reproduce the bug (in most cases this will also mean uploading a demo budget file)

### What happened?

Steps to reproduce:
1. Create a schedule with some splits
![image](https://github.com/user-attachments/assets/34e5dff6-2ee5-4326-82a4-98c10fcfac71)
![image](https://github.com/user-attachments/assets/c29daace-5c5b-4e67-be5c-e92f25dc4fda)
![image](https://github.com/user-attachments/assets/c6eefd33-ea94-40b6-a777-02910932bc14)

2. Set the schedule so that it shows up as Upcoming
![image](https://github.com/user-attachments/assets/4698d54f-66ec-47c0-89fb-22036f8fd531)

3. The split error is shown even though the amounts are balanced  

### Where are you hosting Actual?

Fly.io

### What browsers are you seeing the problem on?

Chrome, Other

### Operating System

Windows 11

**Comment by joel-jeremy** [comment]
For visibility - @jfdoming

**Comment by jfdoming** [comment]
> For visibility - @jfdoming

Yes thanks for triaging! I took a look yesterday and was struggling to root cause. But I'll keep at it

**Comment by alter3d** [comment]
If it helps with root cause, I can confirm that this also happens under the following scenarios:

- Firefox on Ubuntu 24.04 (syncing to self-hosted AWS EC2 instance)
- Firefox on Win10 (same sync server as above)
- Native Windows application (same sync server as above)
- Native Windows application (no sync server)

All running current 24.9.0 build.

**Comment by sjones512** [comment]
Noticed this today.

Windows 10
Firefox 130.0.1
Actual Budget v24.10.1

Not sure if it helps but it also shows when the split scheduled transaction is collapsed:
![image](https://github.com/user-attachments/assets/b1d38aed-82bd-4e31-9a88-b789ce078b28)

Probably irrelevant that the errant transaction split doesn't obfuscate the amount.

**Comment by sjones512** [comment]
@jfdoming I took a look at it and considered attempting a PR but don't feel familiar enough with the code to know I wont break things.

As a kludge it seems like you can just add `update = recalculateSplit(update);` to the end of the rules.ts `execActions` function.

I believe the root cause lies in this block of code 
```
for (const action of childActions) {
    const splitIndex = action.options?.splitIndex ?? 0;
    if (splitIndex >= update.subtransactions.length) {
      const { data, newTransaction } = addSplitTransaction(
        newTransactions,
        transaction.id,
      );
      update = recalculateSplit(newTransaction);
      data[0] = update;
      newTransactions = data;
    }
    action.exec(update.subtransactions[splitIndex]);
  }
```

In this block the amounts of the split subtransactions don't appear to be populated until after `action.exec` is called, but we are doing the `recalculateSplit` before that, in the loop. 

I'm not very familiar with the code, but it seems wasteful to recalculateSplit on every iteration of the loop. I would think it could just be recalculated at the end after all of the subtransactions have been added.

**Comment by sjones512** [comment]
> @sjones512 Yeah sorry I dropped the ball on this one. I want to do a larger refactor to avoid these problems and add some unit tests. Are you okay to wait for that? I will get to it soon but work is killing me right now 😞

Totally your call. It is a fairly intrusive UI bug when it happens, but I think it can be worked around by setting the last split rule as "a portion of the remainder" instead of "fixed-amount".

I'm not familiar with Actual's release process. If you think you'll be able to include the refactor in the next release, there is no reason to merge this. If not, this could be a band-aid to resolve the immediate issue, and a separate issue could be raised for the refactor.

Either way, good luck with work! 💪
