### ISSUE TITLE
[Bug]: CSV duplicate matching no longer showing in the import window.

### ISSUE THREAD

**Issue by youngcw** [actualbudget/actual#3416]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue
- [X] I will be providing steps how to reproduce the bug (in most cases this will also mean uploading a demo budget file)

### What happened?

The CSV importer is supposed to show matching transactions so the user can decide to force import or allow matching and deduplication.  That is no longer happening in the current version.  It quit happening somewhere between 24.8 and 24.9.

The quickest way to test is to either use a existing csv and import it twice, or to make an export of a test budget account, then to reimport it and see that its not matching any of the transactions.  Compare against the deploy for v24.8 to see the difference. https://deploy-preview-3179.demo.actualbudget.org/

### Where are you hosting Actual?

None

### Operating System

None

**Comment by UnderKoen** [comment]
I have done some debugging and found the fix/problem before #3413 . In [#3234 ](https://github.com/actualbudget/actual/pull/3234/files#diff-6adf1923969eafc6e96b9ca5f9fa311c351aedefd4c04b7151fffd7ec9a642ddR1286-R1289) they use the wrong property and incorrect type check.

For #3413 I suspect that the problem is with rerenders. When trying to import a CSV it keeps refreshing and doing weird stuff
