### ISSUE TITLE
[Bug]: Budget Goal Templates - Cannot combine "repeat every X months/years" and "up to" 

### ISSUE THREAD

**Issue by ChiaraBells** [actualbudget/actual#3504]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue
- [X] I will be providing steps how to reproduce the bug (in most cases this will also mean uploading a demo budget file)

### What happened?

I am having trouble with a specific kind of budget template. The [documentation](https://actualbudget.org/docs/experimental/goal-templates/) provides a number of examples, including the following:

`#template $10 repeat every 9 weeks starting 2025-01-04 up to 30`

This works perfectly. The following two examples (with months/years instead of weeks), however, do not work:

`#template $10 repeat every 9 months starting 2025-01-04 up to 30`

`#template $10 repeat every 9 years starting 2025-01-04 up to 30`

When clicking on "check templates" I see the error "There were errors interpreting some templates: [...]".

I do not see any reason why this type of template would not work.

In the documentation, all templates including months or years don't include "starting ..." but rather "by ...". Therefore I also tried combining the following, which all end in errors:

`#template $500 by 2025-03 repeat every 6 months up to 600`
`#template $500 up to 600 by 2025-03 repeat every 6 months`
`#template $500 by 2025-03 up to 600 repeat every 6 months`

It would be great if this bug could be fixed / this functionality could be added to months and years as well as weeks. If there is a way to do it already, it would be awesome if that could be included in the documentation. 

### Where are you hosting Actual?

None

### What browsers are you seeing the problem on?

Firefox

### Operating System

Windows 10

**Comment by youngcw** [comment]
does it work if you add an up to as a separate template? for example add the repeat template on its own line then add a `#template up to 30` on its own line?

**Comment by youngcw** [comment]
Im going to close this as the docs don't show that you can use both repeat and up to together.  Try using separate lines like mentioned above.

**Comment by Mikhail773** [comment]
From what I gathered when I placed up to in a second line it would take the full amount rather than spreading out the amount equally. Also, there is a false equivalency here. You can repeat every x week, but not every x months. When trying with months it requires you state "by" , but that may not always be what you want. Say you want to frontload a budget in January to cover Jan-Mar for $600. You wouldn't want $200 each month which is what by would give you. For some reason weeks let's you frontload, but it's not a viable alternative to months since 12 weeks isn't equal to months.
