### ISSUE TITLE
Obvious slow loading of some of the budget info/settings

### ISSUE THREAD

**Issue by youngcw** [actualbudget/actual#3524]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue
- [X] I will be providing steps how to reproduce the bug (in most cases this will also mean uploading a demo budget file)

### What happened?

This isn't really a bug, but at very least its become worse for me lately.

When the budget loads, certain bits of data are correct from the first render, but not all the data/settings are available from the first render.  This causes the page to progressively update as that data becomes available.  I've attached a screen recording that shows what Im seeing.  Its much worse on my phone using my real budget.  I think a similar thing is happening on the mobile accounts page where the balances all start at 0 then update after a second or two.

The bits of data/settings that I've seen be affected by this are:
Goal data (goal value and long goal)
Privacy mode
Category Notes

Can these bits of data/settings be made to be available at first render?  The category budget, spent and balance fields are, so why not the other bits of info?

I cant seem to get it to happen the demo, so it may have been introduced since the 24.9.0 release.

To recreate:
1.Open the edge build
2. view as many months as you can 
3. turn on privacy mode
4. add some notes and or templates (the goal is to add as much data to the screen as possible)
5. refresh the page a few times and watch closely.  Sometimes its more noticeable than others.

[progressive_load_cut.webm](https://github.com/user-attachments/assets/a0c19671-19b0-4e34-8fa4-2f6f651dcdde)

### Where are you hosting Actual?

None

### Operating System

None

**Comment by MatissJanis** [comment]
The move to `SyncedPrefs` would have caused the privacy mode toggle (and other synced prefs) to appear to be a bit slower. Each time it loads a preference - it performs a separate call to the backend. Individually that's super fast, but if there are hundreds of calls - things can get slow.

There's definitely an optimization we could do here (i.e. fetch all synced prefs and store in redux state; and then just get them from the state instead of backend). I'll look into updating that after the upcoming release.

As for the other things: no immediate ideas.

**Comment by youngcw** [comment]
A note one this: it looks like, at least the template data, doesn't load until after a sync has finished. I haven't tested this on desktop but that looks to be part of the reason on mobile.
