### ISSUE TITLE
[Feature] Support export/import of rules

### ISSUE THREAD

**Issue by psybers** [actualbudget/actual#3591]
### Verified feature request does not already exist?

- [X] I have searched and found no existing issue

### 💻

- [ ] Would you like to implement this feature?

### Pitch: what problem are you trying to solve?

The rules page should allow export (probably in JSON format?), either all rules or the selected set.  And then also allow importing rules.

This could be useful for sharing rule sets.

Another use case (mine) is to clean up the rules, where I have a bunch of 'pre' rules that I really want to move to 'default' but I don't want to edit 30 of them one at a time.  A quick export, find/replace in the JSON, and re-import would be nice.

If we allow import, it would be nice to 'dedupe' and skip importing exact duplicates.

### Describe your ideal solution to this problem

Ideally, the rules page would allow selecting rules and then have a way to export.  Then the selection would export.  If no selection is made, all rules would export.

There would also be an import button/menu item.

When importing, there probably needs to be some sort of exact duplicate checking and skip those.

### Teaching and learning

The docs would need a small section on the rules page describing how you can export and import them.

**Comment by RoLYroLLs** [comment]
Just curious, as a new user, I wanted to use a feature like this, but it does not exist, yet it was closed as "completed". Is that a mistake? I'm not sure if I should comment on here, or open a new issue, so I'll take the safe route and comment here first.

---

I'm not the first to use this app and I won't be the last, and thank you for creating and maintaining it. With that said, I'm sure many users have come across having to create the same or very similar rules.

I'd love to see the ability to import rules created by the community. Sure, not everyone may have or want the same rules as others, but I'm sure we all have many rules that are the same. Of course this is an assumption since I don't have an stats to show.

For example, I'm sure there are many users who have a rule, whether created manually or automatically, that goes something like: "if `imported payee` contains `Publix`, set `payee` to `Publix`".

This, of course, is coming from someone who is just starting to set this up, so this feature is more for new users, and probably rarely used by those who've been here long. However, I can see where even as an experienced user, I can learn from someone's "really cool rule" which prolly does something I've never thought of that might end up useful to use for many of my other rules.

As the documents say you should only really import about 1 month's past transactions, but as OCD as I am, I want to see how my finances have been performing. I was almost tempted to import two year's worth, but decided to only go as far back as January, 1, 2025 (7 months). I know it's going to be a lot of work for me, but I'm down for it as I've been doing my own budgeting for the past 10 years between Quicken then Excel (when Quicken was no longer free on Mac and the old one didn't work anymore). To each their own.

I'm sure if this is ever implemented, it might not be useful for me (unless I find a "really cool rule" to use), but maybe this feature may help new future users.

After thought:
Actually, I just thought about this, what about those users who may want to manage multiple files for whatever reasons, or decide they want to start over. They'd have to recreate the rules from scratch (or automatically). This feature would benefit those and maybe other scenarios that I have not thought of.

**Comment by psybers** [comment]
The project automatically closes feature requests (but not bugs).  Features remaining to be worked on have a "needs votes" tag on them.  You can vote by thumbing up the first comment.

**Comment by RoLYroLLs** [comment]
> The project automatically closes feature requests (but not bugs). Features remaining to be worked on have a "needs votes" tag on them. You can vote by thumbing up the first comment.

Awesome thanks for the info. I just realized I didn't read the full message by `github-actions`. Please accept my apologies.

**Comment by Th0masL** [comment]
I agree that this would be an interesting feature.

I was even thinking we could have predefined/shared rules by country, for example, which would simplify the automatic detection of the categories.

**Comment by Enqueued** [comment]
As a new-ish user I think this would be really helpful.
For instance, when you're setting up a new budget file and you cannot easily migrate accounts between on/off budget it would help with migrating rules to a new file where you have the accounts setup properly 
It would also help out by setting up rules per account so if a friend and I use Actual and the same bank then we can share advanced rule sets between us.
