### ISSUE TITLE
[Bug]: Duplicated transactions with Bank Sync

### ISSUE THREAD

**Issue by cooper-fm** [actualbudget/actual#3762]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue
- [X] I will be providing steps how to reproduce the bug (in most cases this will also mean uploading a demo budget file)

### What happened?

Hi,

I've got a common problem with bank sync in that it's pulling in duplicates for some accounts, see the attached.

I've tried deleting them (they come back), reconciling the account (they come back). The only way I can clear these off permanently is by adding the opposite debit or credit, but pretty much defeats the purpose.

Any clues to fix this?
![Screenshot 2024-11-01 at 08 17 21](https://github.com/user-attachments/assets/cbabffcf-b549-4eab-9300-d7dcaca11b60)

Many thanks

### Where are you hosting Actual?

Locally via Yarn

### What browsers are you seeing the problem on?

Chrome

### Operating System

Mac OSX

**Comment by MatissJanis** [comment]
The problem is most likely the bank sending duplicate transactions OR mutating transaction IDs. A custom bank adapter might solve this problem. 

Either way - first step would be to reach out to the community on discord for all bank-sync related problems. They will be able to assist further.

<img width="1261" alt="Screenshot 2024-09-09 at 19 20 14" src="https://github.com/user-attachments/assets/3d77be04-96c7-46b7-ae27-d1e0a3c9388f">

**Comment by piotrsmykaj** [comment]
The problem still exists and it's well explained there https://www.reddit.com/r/actualbudgeting/comments/1da173b/duplicate_transactions_with_bank_sync/
It looks like it's not one bank issue.

**Comment by lazynooblet** [comment]
I'm having the same issue. Have reported on Discord but didn't get a response. I think the issue is that uncleared transactions are synced with `imported_id: undefined` but the cleared transaction comes in with a defined id.

Reading other issues and community posts there are multiple banks that do this, so perhaps Actual could accommodate for it? Matching date/time/payee/amount on an uncleared transaction with no `imported_id`
