### ISSUE TITLE
[Bug]: Import from YNAB4 not working in release 22.10.25

### ISSUE THREAD

**Issue by yoyotogblo** [actualbudget/actual#378]
### Verified issue does not already exist?

I have searched and found no existing issue

### What happened?

When trying to import from YNAB 4, the importer goes to a blank white screen. There's no error message and no message in the browser's console.

![image](https://user-images.githubusercontent.com/31814048/198822537-bab8be09-5344-493c-b241-06c6b3120562.png)

### What error did you receive?

Blank screen

### Where are you hosting Actual?

Docker

### What browsers are you seeing the problem on?

Chrome, Microsoft Edge

### Operating System

Windows 11

**Comment by spezzino** [comment]
Same happens with the YNAB5 importer, an error is shown to the user

<img width="545" alt="image" src="https://user-images.githubusercontent.com/2013367/198865836-a868ae3b-b593-418a-a37c-f8db2d0e7c9e.png">

**Comment by ijecode** [comment]
Replicated here with latest Docker image (server 22.10.25) running on fly.io. Nothing in the console/network request of any interest as far as I can see.

**Comment by rich-howell** [comment]
Hey @spezzino & @ijecode 

I am not sure what is going on here, I think we might need @jlongster to have a look over this one, I am really sorry about this. 

Cheers
Rich

**Comment by rich-howell** [comment]
@ijecode I don't suppose you have a YNAB export we could test with?

**Comment by yoyotogblo** [comment]
[Test Budget.zip](https://github.com/actualbudget/actual/files/9895629/Test.Budget.zip)

Here's a YNAB 4 one with a test budget I created.  

@TomAFrench made a bunch of changes to the importers so he might be a good person to take a look. Here's one of his PRs: https://github.com/actualbudget/actual/pull/230

**Comment by nintendoeats** [comment]
I am also having this problem, both Windows 10 and Linux Mint, via Vivaldi, Firefox and Edge.

My minor contribution: I was hosting this in a VM on my NAS, and I monitored the traffic on the NIC to see if it was actually uploading the file. the answer seems to be no, as there was no traffic associated with clicking the upload button.

**Comment by MatissJanis** [comment]
Started debugging the issue. Found two issues so far

**First:** Both nYNAB and YNAB4 fails with the following error message: `net.connect is not a function`. This is coming from the kcab worker. It's not able to set up the socket connection.

**Second:** YNAB4 crashes with blank screen because we are missing a `else` return statement [here](https://github.com/MatissJanis/actual/blob/master/packages/loot-core/src/server/main.js#L1847-L1852). The YNAB4 API request is interpreted as "success" and hence the user is redirected to the next page. But because the budget has no data.. we see a blank screen.

I will see if I can continue investigating tomorrow. Signing off for today.

**Comment by jlongster** [comment]
This will be fixed in https://github.com/actualbudget/actual/pull/386
