### ISSUE TITLE
[Bug]: server-url related errors are not surfaced

### ISSUE THREAD

**Issue by MatissJanis** [actualbudget/actual#3784]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue
- [X] I will be providing steps how to reproduce the bug (in most cases this will also mean uploading a demo budget file)

### What happened?

https://github.com/user-attachments/assets/2ebf28e0-0f2e-4c20-8907-5c64651f1f65

### Where are you hosting Actual?

None

### Operating System

None

**Comment by shb9019** [comment]
Hi @MatissJanis, I'd love to take this up if no one's already working on it! I believe this regression was caused due to https://github.com/actualbudget/actual/pull/3736, where we're silently suppressing the URL validation error. This behavior was alluded to in https://github.com/actualbudget/actual/pull/3736#pullrequestreview-2396004709.

**Comment by MatissJanis** [comment]
Feel free to send a PR for this. :)

**Comment by MatissJanis** [comment]
cc @MikesGlitch as an FYI

**Comment by MikesGlitch** [comment]
Oops
