### ISSUE TITLE
[Bug]: Goal Directive does not recognize symbols

### ISSUE THREAD

**Issue by ctrenthem159** [actualbudget/actual#3937]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue
- [X] I will be providing steps how to reproduce the bug (in most cases this will also mean uploading a demo budget file)

### What happened?

When using the `#goal` directive, it fails when adding symbols such as $ or , to your currency.

Normal `#template` directives allow for formatting your currency so you can put `#template 500`, `#template $500` or `#template $5,000.00` but with the `#goal` directive, you can only use the first format.

The documentation does not clarify this limitation, and implies that you can use formatting with `#goal` the same was as you can with `#template`

### Where are you hosting Actual?

Docker

### What browsers are you seeing the problem on?

Chrome

### Operating System

Linux

**Comment by youngcw** [comment]
Commas don't work and will fail parsing even in template lines.  That limitation is in the docs already.  There really isn't a reason to add the currency symbol since "$" is the only one supported anyway.  Really we should make any currency symbol fail the parsing and not be allowed anywhere since it doesn't do anything useful. In the future once there is a gui that wont be used anyway.

Feel free to update the docs to add that extra part about the goals.
