### ISSUE TITLE
[Feature] Templates/Goals tied to an accout?

### ISSUE THREAD

**Issue by Sc00tz** [actualbudget/actual#4043]
### Verified feature request does not already exist?

- [X] I have searched and found no existing issue

### 💻

- [ ] Would you like to implement this feature?

### Pitch: what problem are you trying to solve?

I have a savings account that I set up for periodic bills. Things like property taxes, car maintenance, things we only pay once or twice a year. 

But when I set a goal or template, I can't set a transfer (or split a transfer) to assign that money to that goal or template. 

What I'm looking for is similar to FireFly-III's "Piggy Bank" feature (https://docs.firefly-iii.org/how-to/firefly-iii/finances/piggy-banks/)

### Describe your ideal solution to this problem

I think the easiest way to implement this would likely be to be able to add splits to transfers so you can assign a "payee" to part of the funds. 

So, for example, you have a transfer from your checking to your savings account, say it's $1000. Within the split you can set $100 for Car Maintenance, $500 for Taxes, and the rest is just general savings. 

That way the $100 and $500 would show up in the Budget view.

**Comment by youngcw** [comment]
Could not use a category dedicated for the yearly bill and a schedule template?

**Comment by Sc00tz** [comment]
> Could not use a category dedicated for the yearly bill and a schedule template?

I'm not sure how that helps me in this instance. 

If I have a yearly bill, how do I allocate the money to that bill until it's up, and how does it get assigned to that bill? Maybe I'm missing something?

Also, that might work for the things like the tax bill, but not so much for random expenses like vehicle or house maintenance.

**Comment by youngcw** [comment]
Categories are for holding funds, so you have a category that holds your tax bill savings. Having a schedule is to aid in planning then, after making a tax schedule, use a schedule template to automatically add funds to your savings category over time. 

The home maintenance one you will need something like a sinking fund since there isn't a single known event. But you still save up in a category same as the other case.

**Comment by Sc00tz** [comment]
I'm still confused at what you're saying, is there documentation for what you're describing, because I can't seem to figure it out. 

If I move money from my checking account to my periodic bill account, it's marked as a transfer, so it's not set to a category, and I can't set it to a category.

**Comment by youngcw** [comment]
If you aren't familiar with envelope budgeting you should read up on it. Actual's docs have some info on it. Also basically everything put out by YNAB applies as well.

Categories in an Actual budget are basically the same thing as a piggy bank from firefly, assuming I'm understanding the page you linked. The primary difference is that categories aren't tied to specific accounts, the funds can live in any account.

**Comment by Sc00tz** [comment]
I guess the thing that I'm not getting, and I'm not finding in the documents.. 

Transactions are set to categories. If I don't have a transaction, how do I set money to a category? If I transfer money from my checking to my savings account, for use for my tax bill, how do I set that to my tax template/goal/schedule, if it's category is set to a transfer and can't be edited?

**Comment by youngcw** [comment]
You add funds to the tax savings by budgeting it to the tax category. 

The transfer isnt spending, the money is still on your budget, so it doesn't get a category.

**Comment by Sc00tz** [comment]
"You add funds to the tax savings by budgeting it to the tax category."

That's what I can't figure out how to do. I have a budget for my tax savings, but how do I know how much I put in it each month, if I can't add anything to spent? Amounts only seem to get added to spent if you set a category for that transaction. 

![image](https://github.com/user-attachments/assets/f70cea10-6fc1-44c8-9834-2fb2e34a9797)

Looking at that picture, I don't know how to say how much is saved, or allocated, specifically for that category item

**Comment by Sc00tz** [comment]
Basically, that balance is always yellow, unless I add the amount to spent and then it makes it green. If I have nothing in spent, the budged amount increases every month by what should already be allocated for that.

**Comment by Sc00tz** [comment]
OOOOHHH, I figured it out, by clicking on the "left to budget" amount when set to envelope budgeting. I prefer tracking budgeting layout, but at least now what's going on makes sense.

**Comment by youngcw** [comment]
Im glad you got some things figured out.  Just to be sure you don't have some misconceptions, here are a few comments on your last posts.

> I have a budget for my tax savings, but how do I know how much I put in it each month, if I can't add anything to spent?

You have to figure this amount out yourself.  The short answer is tax_bill/12, but you will have to estimate what the tax bill is.  Using templates just automates adding to the "Budgeted" column on the budget, nothing more.

> Amounts only seem to get added to spent if you set a category for that transaction.

Yes.  The only things that get categories are money leaving the budget (spending), or money entering the budget (income, refunds, etc).  Transfers don't get a category if between on budget accounts since the money didn't leave or enter your budget, ie a net 0 change.

> Basically, that balance is always yellow, unless I add the amount to spent and then it makes it green.

The green and yellow coloring are based on templates/goals that you added to the notes.  So if you aren't sure what the templates are doing then the colors are just going to be more confusion.  Also, you can hover the category balance to get some insight into what the template is requesting and what you have left to reach the needed amount.


> If I have nothing in spent, the budged amount increases every month by what should already be allocated for that.

Yes, you are saving funds inside the category.  The idea is that once you get to when you need to pay the tax bill you have enough to pay the bill in just that category because you were deliberately saving.  I think you understand this now based on your last comment.

**Comment by Sc00tz** [comment]
Thanks for your help working through this, I really appreciate it :)
