### ISSUE TITLE
[Feature Request] Improve server security against attacks

### ISSUE THREAD

**Issue by rich-howell** [actualbudget/actual#515]
### Discussed in https://github.com/actualbudget/actual/discussions/174

<div type='discussions-op-text'>

<sup>Originally posted by **blakegearin** June  2, 2022</sup>
Currently a password authenticates a user to access a server. In addition to OAuth2, OIDC, LDAP, SSO support (#61), it would be worth exploring additional security features to make users feel more comfortable when self-hosting.

1. adding email to the login form
1. email alerts for multiple incorrect password attempts
1. re-authenticate when exporting
1. options to restrict login based on amount of concurrent users or browser/device
1. 2FA/multi-factor authentication
1. OTP ([`yubikey`](https://www.npmjs.com/package/yubikey))
1. CAPTCHA ([`svg-captcha`](https://www.npmjs.com/package/svg-captcha), [`react-simple-captcha`](https://www.npmjs.com/package/react-simple-captcha))</div>

**Comment by MatissJanis** [comment]
👋 The next release will feature e2e encryption. It's not exactly what's discussed here, but it will be a big improvement in terms of security.

Some commentary on the suggestions:

(1) - why?

(2) - this is interesting and could be done; also with lockup period for the budget file if multiple login attempts failed

(3) - not possible due the nature of the offline-first app. You already have ALL the database locally. What protection does adding a login box for local data give? Nothing really. Just a gimick.

(4) - same problem here due the nature of offline-first architecture

(5, 6) - definitely something we could explore

(7) - IMO not worth it, but happy to be proven wrong

**Comment by j-f1** [comment]
Re 5/6, it would be nice to have support for [Passkeys](https://developer.apple.com/wwdc22/10092) (which are supported across platforms) so that folks get high security without needing to remember a password. This uses WebAuthn so folks who are extra security conscious could pop in an external security key instead.

**Comment by MatissJanis** [comment]
:wave: Thanks for the idea! It seems that this has not gained traction so far.

In order to keep our backlog of issues in order I'll close this one off. But if you are still interested in building this - please open up a new issue where you outline the proposal or open up a PR and we can discuss further there.
