### ISSUE TITLE
[Feature] Projected Balances Report

### ISSUE THREAD

**Issue by rich-howell** [actualbudget/actual#517]
### Discussed in https://github.com/actualbudget/actual/discussions/187

<div type='discussions-op-text'>

<sup>Originally posted by **ouhakheme** August 15, 2022</sup>
Once Actual is stable and mostly feature complete, I'd love to see a Projected Balances Report.

Take all current transactions to date on one account + scheduled transactions (monthly, quarterly, yearly) = Projected Balance in the future.  If we could also add scenarios where we gain income, or make a large purchase, it would update the chart, and provide insight in when/how you should change course.  Being able to see 1yr+ into the future would be fantastic.

Pocketsmith currently has the best implementation of this feature that I've seen. </div>

**Comment by nistvan86** [comment]
I'm heavily using MoneyManagerEx's Cash Flow report which can project into the future (up to many years). It supports daily and monthly cash flow with filtering over one or multiple accounts and custom date ranges. The result is both shown in a chart as well as in a table. Something similar would be amazing here.

(I would really love to move away from MMEx to something else, as it's mobil app and desktop app is drifting away in compatibility hopelessly. Actual seems very promising.)

**Comment by mk-french** [comment]
I was a Pocketsmith user a while back and can agree that the projected balance feature was very well implemented. 

I've actually started having a hack around to implementing this. I've made some progress (and probably broke a few things), but I'd be keen to get some feedback on if I'm heading in the right direction before I head to far into the woods.

I'm not a front end developer by any stretch, but okay at looking at examples and extending... There's a few edge cases like transfers that I'm dealing with but I'll get something up soonish for some guidance. :)

**Comment by brasswood** [comment]
Is this similar to my feature request at #2039?

**Comment by CrazyKidJack** [comment]
Would be nice if, in addition to current balance + scheduled transactions, it also allowed you to take into account your budget. Mainly because a lot of my spending is not in scheduled transactions. the big / predictable stuff is. But things like groceries and gas are not even though those are relatively large expenses because there's no way for me to know in advance when I need to go to the store.

To enable this, maybe it could let you select from one or more of the following options or something:
- create forecasting budget
- assume this month's budget, applied every month
- assume last month's budget, applied every month
- assume average budget of last 6 months, applied every month
- assume average budget of last year, applied to every month
- assume average budget of YTD, applied to every month

**Comment by alexgug** [comment]
For my part, I'm currently using Microsoft Money since... like 10 years. And the feature for Forecasting the cash flow is incredibly usefull ! 
I want to move to a newer interface, available on docker (so I can access it from almost anywhere with my setup), and Actual Budget fit my needs. Just miss the forecast !

**Comment by axjasf** [comment]
I would also want such a feature.

**Comment by AntoninoBonanno** [comment]
related : #6484
