### ISSUE TITLE
[Feature] Possibility to add a note to the schedule payments

### ISSUE THREAD

**Issue by rich-howell** [actualbudget/actual#519]
### Discussed in https://github.com/actualbudget/actual/discussions/243

<div type='discussions-op-text'>

<sup>Originally posted by **fstybel** September  5, 2022</sup>
I would like to create multiple scheduled regular payments but I'm worried that I will forget for what purpose each of them was created. So, I would like to have the possibility to add a note (like for transactions) to each of them. </div>

**Comment by rickdoesdev** [comment]
This seems to duplicate https://github.com/actualbudget/actual/issues/578 where some further discussion has been had including an older PR

**Comment by rickdoesdev** [comment]
@MatissJanis apologies for the direct ping especially if this isn't for you, but you seem to be the active on in the issue management from what I can see in docs and activity. There's a few feature requests that are all boiling down to roughly the same set of changes around making schedule entry more like transaction entry. Is there a way we can merge these into a single point so the votes aren't being scattered across multiple similar requests?

Here's a small cluster of very similar issues, probably a few more that I've missed.

- https://github.com/actualbudget/actual/issues/578 Add notes to schedule
- https://github.com/actualbudget/actual/issues/909 Display schedule name as note name
- https://github.com/actualbudget/actual/issues/1973 Add Category and Notes to schedule
- https://github.com/actualbudget/actual/issues/1570 Add Category to Schedule (including this because it's related to the one above)

**Comment by matt-fidd** [comment]
These can be added through the rule and will display in the UI
