### ISSUE TITLE
[Feature] Support applying Categorisations to single, single and future, or all Transactions in UI

### ISSUE THREAD

**Issue by rich-howell** [actualbudget/actual#529]
### Discussed in https://github.com/actualbudget/actual/discussions/153

<div type='discussions-op-text'>

<sup>Originally posted by **winklevos** August  6, 2022</sup>
  When categorizing a transaction, ability to choose
        - Apply only to this transaction
        - Apply to all future matching transactions
        - Apply to all future and past matching transaction</div>

**Comment by MatissJanis** [comment]
This is an interesting proposal and definitely one that I would support. Oftentimes I find myself having to manually categorize transactions from the same payee, because somehow the automatic-categorization logic just isn't working for it..

The ability to manually tweak this __during__ transaction creation is an interesting idea.

From a UX perspective this might be a tricky problem because we don't want to always pop-open a modal when creating a transaction. This functionality should be subtle and elegant.
