### ISSUE TITLE
[Feature] Ability to add tags to transactions

### ISSUE THREAD

**Issue by rich-howell** [actualbudget/actual#531]
### Discussed in https://github.com/actualbudget/actual/discussions/151

<div type='discussions-op-text'>

<sup>Originally posted by **winklevos** August  6, 2022</sup>
Add a field to capture tags onto a transaction for later filter, 

i.e tag a transactions with `tax` `one-off`</div>

**Comment by MatissJanis** [comment]
@winklevos 

Although we currently don't fully support search by tags, you can still use the notes field for them.

For example: `#tax #one-off` in the notes field

Given this: closing

**Comment by albertogasparin** [comment]
Hello, not sure what was discussed in #151 as it shows locked with 0 comments, but I'd like to add another reason why tags can become very useful: reporting and overview.

For instance, I do have a holiday category. I currently use notes as a way to group expenses by holiday destination but it is hard to visualise the impact of each on my yearly monthly budget. I have to manually select transactions in order to see their totals, and if in the future we will have better reports (for instance by category) it would be great to group by tags.
 
Hope it makes sense.

**Comment by Kidglove57** [comment]
100% agree with this suggestion

**Comment by GurjinderSingh** [comment]
currently I am using Firefly and it have tags based on rules. multiple tag can be used
https://demo.firefly-iii.org/transactions/edit/450

only problem with Firefly is refund transactions are not allowed and developer said its accountant suggestion

**Comment by YagiOoda** [comment]
I would really like this feature however it is implemented. I think even using the notes field and autocompleting based in "#" would be really helpful!

**Comment by tam481** [comment]
👍

**Comment by jimmys888** [comment]
> I would really like this feature however it is implemented. I think even using the notes field and autocompleting based in "#" would be really helpful!

Second this. Most of the time I forget what tags I've entered in the past, so using autocomplete when typing `#` in the notes field is beneficial. Maybe a dedicated page to manage the tags? If a tag that's not in the tags list is entered, the user should add it to the list to appear in the autocomplete.

**Comment by Kidglove57** [comment]
I would also ideally like this tag feature to be implemented. I have a decent workaround at the moment. I enter a note in tag style in the notes field. I have quite a number of saved filters which reference specific "tags" and thus enable me to gather all the data I need.

**Comment by jimmys888** [comment]
> I would also ideally like this tag feature to be implemented. I have a decent workaround at the moment. I enter a note in tag style in the notes field. I have quite a number of saved filters which reference specific "tags" and thus enable me to gather all the data I need.

That is a good idea. It's just that I often forget what tag(s) I entered for a transaction, and when I'm doing the same transaction I have to look for the older ones to see what tags I assigned. Autocomplete feature will help a lot.

**Comment by apilbeam101** [comment]
Very much like this idea too. 
Particular use-case in mind for me would be thigs like holidays and work expenses. 
I would like my actual categories to reflect the purchase type, i.e Flights, Hotels, Food, Activities etc. but then the ability to tag specific spend as "Holiday" or "Work Expenses" means that I can see the breakdown of my costs when travelling as well as be able to ignore my work expenses since they'd be claimed back.

**Comment by Rick-Thomas** [comment]
I'm all for TAGs...    Without this you have to _OR_ **duplicate** the categories to identify the elements your tracking _OR_ **filter** using the Notes field, hoping you have a uniform method to identify the elements your tracking...

**Comment by thoughtlessmind** [comment]
this would be a good addition to manage the subcategory or specific parts of the transactions. Suppose, I want to tag the expenses by the medium they spent, like credit card, direct transfer, UPI, etc. Right now, it's only notes (as suggested above), but that is not optimized as it can't be used in analytics or anywhere efficiently.

**Comment by MikesGlitch** [comment]
Personally I've started using the notes field for tags like "#interest" and I've found it works great with reporting.

I've created a saved filter for it - "Bank account interest" - applied it to the report and I'm thinking it's a good solution.

I think the downside to adding a new field for tags is we'd be making a new field for something that already "sort of" exists with notes. Maybe Notes should be enhanced, rather than a new thing developed.

Maybe this is a styling issue. If there was a set of tags that you have already used in a notes field, maybe we could save them somewhere for re-use in notes. And we could style it like this: 

![image](https://github.com/actualbudget/actual/assets/5285928/27d17207-bf3d-4421-a043-bc35657e507f)

We already have different displays for when we're editing the field vs viewing - so I'd think the "View" would just change to recognise "#{thetag}" and when it see's the hashtag it styles it.

When we're entering the field, we could use the autocomplete control and trigger it when the input see's a "#". That would then trigger the normal autocomplete but with a list of tags:
![image](https://github.com/actualbudget/actual/assets/5285928/7d3437fb-be04-48d7-9663-986059ec6180)

**Comment by Kidglove57** [comment]
@MikesGlitch I do exactly the same as you for any group of transactions I want to report on. A special home project, data for tax etc. Eg #GiftAid, #Interest or #Summerhouse

**Comment by thoughtlessmind** [comment]
yes @MikesGlitch 
that makes much more sense. there's already a relevant field so creating and managing a new similar field would be useless. 

in notes, we can improve how a particular tag is treated, like a suggestion, formatting, bulk edit text of a particular tag, and all..

**Comment by shawalli** [comment]
I would love this feature, but I would recommend it be its own field. I think about it like I do for tagging other things. Take the most common programming example, a blog. One of the first things you add to a blog post are tags. They usually have their own input, have auto-complete for existing tags, and support multiple tags. The order doesn't matter, and you can filter by multiple tags.

**Comment by carkom** [comment]
I'm not convinced that we'd need a new field just for tags. There's no reason you can't have multiple tags in the notes field and there's already functionality to filter by one or multiple tags that are currently in the notes (example screenshot below). The only thing we are missing to make this an integrated feature is auto-complete (which I think everyone agrees on) and formatting (like @MikesGlitch displayed). You could even create a new filterBy type for "tags" that just searches the notes field and uses the aformentioned auto-complete.

![image](https://github.com/actualbudget/actual/assets/55785687/13d313d1-0c6c-4633-83ac-9aaede5bb2ce)

**Comment by Teprifer** [comment]
> I'm not convinced that we'd need a new field just for tags. There's no reason you can't have multiple tags in the notes field and there's already functionality to filter by one or multiple tags that are currently in the notes (example screenshot below). The only thing we are missing to make this an integrated feature is auto-complete (which I think everyone agrees on) and formatting (like @MikesGlitch displayed). You could even create a new filterBy type for "tags" that just searches the notes field and uses the aformentioned auto-complete.
> 

I like this approach, a separate column would change available estate, and I suspect adding tags would reduce the need for lengthy notes - sort of an add 1 here, sub 1 there type thing so the sum space needed is about the same.

**Comment by shawalli** [comment]
I can’t get behind that…with searching though, I’d like for the tags to be able to be unordered. For example, “#taxes #hsa” and “#hsa #taxes” should return the same results.

**Comment by Teprifer** [comment]
> I can get behind that…with searching though, I’d like for the tags to be able to be unordered. For example, “#taxes #hsa” and “#hsa #taxes” should return the same results.
> 
> EDIT: can’t -> can

I'd assume tags would default to the contains option for each select, a slightly nicer way of using:

![image](https://github.com/actualbudget/actual/assets/34882928/9622a214-914c-41bb-ad3c-6a166d1ad4b6)

**Comment by CodingEmil** [comment]
Are there any news to this?

**Comment by CodingEmil** [comment]
Is there any news to this?

**Comment by lelemm** [comment]
I was trying to tackle this feature based on some messages here, adding tags in notes looks easy but the input component must be rebuild from scratch using a div (with ContentEditable) instead of a input. This open for so many possible problems since it does not have .value attribute.

Any way, the way I made a POC. The video below shows it:

https://github.com/actualbudget/actual/assets/15043428/a110b200-91c8-41f0-a0ef-0e4779d31483

This is far for ready, there are too many events missing (since I changed from input to div). It's just to showcase a possible way to implement this if it makes sense.

WDYT @MatissJanis ?

**Comment by MatissJanis** [comment]
@lelemm I'm currently vacationing, so can't do a deep dive this week. But take a look at #2670

**Comment by youngcw** [comment]
@lelemm Have you look at #2670?

**Comment by lelemm** [comment]
I just noticed that @MatissJanis / @youngcw . Looks like they took different approach on this

**Comment by lelemm** [comment]
Played around with their version. Looks very nice. There are two main differences as I can see: 
- I tried to use an WYSIWYG approach, they set the tags after done editing the input.
- I added a different filter type (has tags) so you can easily search for notes with multiple tags on it without thinking about the order and without using regex

**Comment by psybers** [comment]
@lelemm Is there a branch/PR somewhere? I think there are things that are nice about both approaches.  We might want to consider a merger.

**Comment by lelemm** [comment]
@psybers here, created a draft PR for it: https://github.com/actualbudget/actual/pull/2869
It's far from usable, for example, I didn't made the tags clickable like @joel-jeremy version and it's missing many events to mimic the original input field

Lint doesn't like what I did cuz of this lines: [raw html](https://github.com/actualbudget/actual/pull/2869/files#diff-1ec67e99a0958784935973fd65f348c2c881f4b83a0229070edad3cf7349afd7R66)

I'm not keep digging this since there is a solution in place for this feature

**Comment by youngcw** [comment]
Initial support added by #2670.  Will be in the next release.
