### ISSUE TITLE
[Feature] Allow editing of account properties after creation

### ISSUE THREAD

**Issue by rich-howell** [actualbudget/actual#532]
### Discussed in https://github.com/actualbudget/actual/discussions/147

<div type='discussions-op-text'>

<sup>Originally posted by **winklevos** August  6, 2022</sup>
As per title, allow modifying of properties of accounts after creation. Some may have downstream effects, so processing or restricting based on those</div>

**Comment by j-f1** [comment]
Looking at the types that can be configured:

- Name: accounts can be renamed ✅
- Type: this appears to only be used in the mobile account list, maybe we can drop it entirely?
- On/Off Budget: can’t be changed currently, might make sense? (workaround: create a new account and then bulk move the transactions over in “all accounts”)
- Balance: just edit the starting balance transaction or add new transactions

**Comment by albertogasparin** [comment]
I came to this feature request because was looking for a way to change On/Off Budget (useful while you are still figuring out how you structure your budgets across accounts).
Great that there is a workaround, but also it might make sense implementing it via a button in the dropdown above "Close account".

**Comment by j-f1** [comment]
Opened https://github.com/actualbudget/actual/issues/753 to track adding docs for on/off budget not being changeable and calling it out when creating an account.
