### ISSUE TITLE
[Feature] Add Bank as parent of Account to allow relation

### ISSUE THREAD

**Issue by rich-howell** [actualbudget/actual#540]
### Discussed in https://github.com/actualbudget/actual/discussions/149

<div type='discussions-op-text'>

<sup>Originally posted by **winklevos** August  6, 2022</sup>
Add a table for bank which can be a parent of accounts</div>

**Comment by MatissJanis** [comment]
👋 @winklevos My recommendation would be: include the bank name in the account name. For example: `[KBC] Main Acount` or `Revolut: savings`.

IMO the added complexity of running and maintaining another layer of accounts far outweighs the benefit we would gain here.

Which is why I'm sadly going to close this.

**Comment by rich-howell** [comment]
Interestingly, this is already in the database 

![image](https://user-images.githubusercontent.com/22135084/216810384-e7a39f21-e9ab-464b-82e3-01322a6b89af.png)

**Comment by j-f1** [comment]
I think that may be used for redirecting transactions on closed accounts?

**Comment by MatissJanis** [comment]
Might also be related to bank-sync.
