### ISSUE TITLE
[Feature Request] Budget indication of scheduled transactions

### ISSUE THREAD

**Issue by rich-howell** [actualbudget/actual#543]
### Discussed in https://github.com/actualbudget/actual/discussions/177

<div type='discussions-op-text'>

<sup>Originally posted by **alpha-beta-soup** May  8, 2022</sup>
Let's say I pay $500 rent every Friday. Some months there are four Fridays in a month, less often there are five. Do I budget $2000 or $2500 in a given month?

Let's also say I have a complex series of subscriptions, tithes, donations, fees, etc. that repeat either weekly, fortnightly, monthy, 6-monthly, annually, bi-annually... but definitely _deterministically_. How much do I budget in these categories?

I should be able to tell, within a budget category for any month, what all of my _scheduled expenses_ are, so I can budget for these known and regular expenses before allocating money to categories to cover my unknown/irregular expenses.

Although I'm new to Actual (recent nYNAB convert due to their massive price hike), I can't see a way to see these expenses reflected in my budget _until after they occur_. I want to budget for them _before they occur_.</div>

**Comment by j-f1** [comment]
This would be handled well by templates IMO

**Comment by CaptainLexington** [comment]
I agree that templates are well-positioned to be a solution to this problem, but I don't think they are the solution by themselves. Templates are essentially a superset of schedules: not all templates indicate a specific future transaction, but _all_ schedules indicate future spending that must be budgeted. To suggest I create a template for each of my schedules is to suggest I create each schedule twice - and to update them twice as my expenses change.

Perhaps there could be a way to refer to a schedule in a template, or derive a template from a schedule (similar to how one derives a rule from a schedule) - with the option to re-derive the template when you edit the schedule, so that they never get out of sync.
