### ISSUE TITLE
Flag account transactions

### ISSUE THREAD

**Issue by rich-howell** [actualbudget/actual#552]
### Discussed in https://github.com/actualbudget/actual/discussions/37

<div type='discussions-op-text'>

<sup>Originally posted by **bdoherty** May  4, 2022</sup>
Option to flag various transactions with different coloured flags.   Toolkit for YNAB allows you to custom name your flags.

![image](https://user-images.githubusercontent.com/335468/166805431-3a6f568a-d1d1-45ba-9482-9979281105fb.png)

![image](https://user-images.githubusercontent.com/335468/166805584-9749b920-6e4d-4184-8c8d-0e0980ae419f.png)

(Source: https://www.eshmoneycoach.com/tutorials/toolkit-for-ynab-account-screen-settings-2/#custom-flags)</div>

**Comment by MatissJanis** [comment]
👋 Thanks for the idea @bdoherty , but may I ask: why? What problem would this solve for you?

I'm asking because perhaps there is a better way how we could solve your problem in Actual. Without fully understanding your problem we are unlikely to commit to a solution.

Hope you understand.

**Comment by Kidglove57** [comment]
I do not want to be a slave to what people have  got used to in YNAB but here is their guide to using Flags:
https://support.youneedabudget.com/en_us/flags-a-guide-Skh8Xb4kj

I cannot convince myself that they add much if anything that cannot be achieved in other ways

**Comment by YagiOoda** [comment]
I agree- I never used YNAB's flags. One thing that would be nice is that instead of flags like YNAB, we could have autocomplete tags in the note field. For example, than you could group one vacation together with the #2023Carribean or whatever!

**Comment by Kidglove57** [comment]
@YagiOoda I am certainly with you on tags. I add them manually in the notes column and keep track of a number of transaction types in that way. I have two tips for their current use in Actual:
1) I add them to all relevant scheduled/repeating transactions so that they auto complete (at least for those transactions )
2) When I need a report for a particular tag type I use the filter tool to drill down to the date range and tag that I need . By then ticking the checkbox to select all filtered transactions I get a total number for that filtered “report”.

it would be brilliant to have the auto complete feature for tags that you mention!

**Comment by rich-howell** [comment]
While this would be nice, one of the core principals of Actual is it's simplicity. I think this would add "clutter" to the screen that only a small portion of users would use, I am also guessing that is why it is in a Toolkit for YNAB and not the core feature set.

**Comment by Kidglove57** [comment]
I think it is the renaming of flags that is in Toolkit but yes, I do agree with you.

**Comment by MatissJanis** [comment]
Looks like we're in agreement here that adding flags to Actual is a **wont-fix** (wont-do?).
