### ISSUE TITLE
[Feature] Allow users to manually set "From last month" in available funds in budget

### ISSUE THREAD

**Issue by rich-howell** [actualbudget/actual#554]
### Discussed in https://github.com/actualbudget/actual/discussions/192

<div type='discussions-op-text'>

<sup>Originally posted by **siegfriedpammer** May 29, 2022</sup>
I am trying to start to use actualbudget to get an overview of my financial situation. I have imported all transactions of all my bank accounts starting from January 2022 and categorized them so I can get an overview of my spending. However, I will only be able to do proper budgeting from May or June 2022. In order to get correct results I would like to be able to set the "From last month" field of May ignoring all the previous months.
I know that I could simply remove all transactions before May or June, but I do not want that, because it is helpful to see past transactions when creating a new budget.
How can I achieve this? Thanks!

Unfortunately I am not a web dev, so I won't be able to contribute. Thank you for your work!</div>

**Comment by rich-howell** [comment]
Hey @siegfriedpammer

Can you ellaborate on what your trying to achive here? 

Cheers
Rich

**Comment by matharman** [comment]
I found this issue while searching for a solution to the same problem. Maybe my 2 cents will help, too.

To get started with Actual, I imported transaction history from my & my partner's banks dating back to July 2019. Because I have no budget or categories set for those transactions, the `To Budget` amount shows that I have way, way more than my current account balances available for budgeting `From Last Month` -- roughly 6x more than my total balance.

It seems like what Actual wants me to do is to set my starting balances on Day 1 and only add new transactions from that day onward.

What I (and I think the OP) would like is to be able to keep our historical transactions to be able to view trends like Cash Flow, but to instruct Actual that I am starting my budget on Feb 3, 2023 -- and my `From Last Month` should only reflect the account balances at that time.

Does that help clarify? @siegriefpammer please do chime in if this description does not sound like what you had in mind, and I'll create a separate issue.

**Comment by matharman** [comment]
I've had a bit more time to experiment, and this bit:

> To Budget amount shows that I have way, way more than my current account balances available

was user error; I set the Starting Balance to the beginning of my transaction history, and categorized all paychecks as Income.

After my experimenting I also think the feature request is better summarized as: allow user to mark the Running Balance of an account on a particular date/transaction as the Starting Balance.

**Comment by j-f1** [comment]
> After my experimenting I also think the feature request is better summarized as: allow user to mark the Running Balance of an account on a particular date/transaction as the Starting Balance.

What do you mean by this? “Starting Balance” is just another transaction in your account history. (the only special behavior is that we look for a payee named that and create one if it’s missing when adding a new account)

**Comment by matharman** [comment]
Sorry, maybe Starting Balance had nothing to do with it -- my transaction history isn't categorized so manipulating the Starting Balance category was the only way I could seem to get the To Budget view to change in an expected way. 

It could be that I am just using Actual totally wrong, but what I'm trying to accomplish is to have my old account history stay uncategorized (it would be cumbersome to go through that 4yr history), but have To Budget value reflect my Running Balance from the day of import. I will of course categorize new & future transactions, so that I can actually budget.

For now my work around is to categorize every "historical" transaction as Starting Balance, but this feels like an abuse of that category.

As the OP mentioned, it seems like the other option currently is to remove all my account history and just set the Starting Balance to its value as of today, and only add future transactions. 

It would be nice if instead I could tell Actual to start budgeting with the Running Balance on the date I imported the transactions, instead of having to categorize the full history.

<details>
  <summary>
My specific case looks like this (collapsed because it's not directly related to the discussion, but might help illustrate my problem).
</summary>

With one account, I have the full transaction history from the time it was opened (2019-present). Since that history is quite long, I don't want to go through and categorize everything as it would be cumbersome; but I want to keep the balance history to look at Cash Flow trends.

Because I have the full history, I set the Starting Balance as a $0 transaction back in 2019. At this point, the To Budget view showed $0 -- probably because nothing is categorized, other than this single transaction.

Next I categorized all my past paychecks as Income to see if I could leave only the outflow uncategorized; but that made To Budget show all my income ever since 2019.

I suspect if I went through and categorized everything, it would work out to the current Running Balance like I wanted. Instead I just marked everything as Starting Balance, which caused To Budget showed the value I expected.

</details>
