### ISSUE TITLE
[Feature] Allow changing the base URL

### ISSUE THREAD

**Issue by Corza** [actualbudget/actual#672]
### Verified feature request does not already exist?

- [X] I have searched and found no existing issue

### 💻

- [ ] Would you like to implement this feature?

### Pitch: what problem are you trying to solve?

I'd like to access my Actual Budget from a subfolder on the domain such as example.com/budget

I am using SWAG reverse proxy.

Currently there is no way to set the base URL and as such, any reverse proxy used in this configuration does not work.

**Comment by anthonymesa** [comment]
I am willing to take a stab at a fix for this. I understand that the actual-server container uses the actual-app npm module. Since you would want the server and the client to both be available at domain.com/route, I assume this fix requires modification of both the actual-app and the actual-server?

**Comment by j-f1** [comment]
Sorry for the delay in replying. It would indeed require a modification of both client and server. Off the top of my head, these things would need to change:

- URLs to the various JS/CSS/image files referenced by the HTML file (currently they all use `/`-prefixed URLs). This is a bit tricky because you can load up e.g. `<actual-server>/accounts/budgeted` and you will get back the same HTML file as if you load the home route, so regular relative URLs won’t work. This would probably have to be done on the server.
- If the external proxy handles stripping off the base URL prefix before forwarding to the Actual server, the server would still be able to serve everything from its root. Otherwise it would have to serve all of its routes with an appropriate prefix.
- `browser-server.*.worker.js` loads `/kcab/kcab.worker.*.js` via `importScripts`
- The bootstrapping logic (#649) works by talking to the root of the current origin, and that would need to be set up some other way (or accept that auto-configuration is not possible when using a non-root base URL)
- The client-side router assumes that it is running at the root, but hopefully `react-router` has an option to set a base URL. You’d need to audit for usage of the raw `window.location` API to ensure there aren’t any issues.

There are probably things that I’ve missed, but hopefully the information listed above is enough to get you up and running so you can more thoroughly test things out and find the things I forgot about :)

The existing frontend *should* work as-is with the API not being hosted at the root (i.e. put `http://localhost:5006/foo/bar` into the server config text field when first using Actual)

**Comment by asfalots** [comment]
IMHO you should use the `proxy_pass` option to trim the `/budget` from the call you made to Actual-server. 
It does not need any application modification, maybe just an explanation in the documentation.

**Comment by j-f1** [comment]
@asfalots That’s not enough to get things working properly — the things I listed in my comment need to be changed too.

**Comment by razorman8669** [comment]
This is still an issue as `actual` doesn't use relative links, and when running actual behind a reverse proxy via paths (instead of sub domains) it doesn't work. 

For my use case, I cannot run it as a subdomain and instead need to change the base URL to a custom path (ie: `mydomain.com/actual`) so I can run it alongside other services on the same server. 

are there any developments to get configurable base URL's in actual?

**Comment by kgadberry** [comment]
I'd also like this to be implemented, if there are any developments.

**Comment by dojoca** [comment]
Really wish this was implemented... it's the last thing holding me back from using actualbudget.

**Comment by JacobDB** [comment]
I'd also like to voice my support for this issue. I like to host things at a path so that I don't have to expose my hosted applications at subdomains. It's a bit of "security through obscurity," and it means I only need to manage one SSL certificate. I might put this at `apps.example.com/actual`, for example.

**Comment by SunFlowerOwl** [comment]
I'd also like to voice my support for this issue.

**Comment by ghost** [comment]
I'd also would like to see this feature added.

**Comment by Leynch** [comment]
+1

**Comment by pcsherid** [comment]
+1

**Comment by sylvainpetit** [comment]
I really wish this was implemented!

On my apache reverse proxy I tried using mod_substitute to rewrite the links in the HTML, but couldn't get it to work...

> \<Location /budget/\>
\# Force plain text for mod_substitute
 RequestHeader unset Accept-Encoding
ProxyPass        http://myserver.mydomain:5006/
ProxyPassReverse http://myserver.mydomain:5006/
\# Tell Apache to inspect the content of these types
AddOutputFilterByType SUBSTITUTE text/html text/javascript application/javascript application/json text/css
\# Fix HTML tags
Substitute "s|href=\"/|href=\"/budget/|i"
Substitute "s|src=\"/|src=\"/budget/|i"
\# Fix internal Javascript paths
Substitute "s|\"/static/|\"/budget/static/|i"
Substitute "s|'/static/|'/budget/static/|i"
Substitute "s|\"static/js/|\"/budget/static/js/|i"
Substitute "s|\"static/css/|\"/budget/static/css/|i"
\# Fix the manifest and other root files
Substitute "s|\"/manifest.webmanifest\"|\"/budget/manifest.webmanifest\"|i"
Substitute "s|\"/site.webmanifest\"|\"/budget/site.webmanifest\"|i"
Substitute "s|\"/favicon.ico\"|\"/budget/favicon.ico\"|i"
Substitute "s|\"/kinto-config.json\"|\"/budget/kinto-config.json\"|i"
\</Location>

**Comment by lorenzonotaro** [comment]
I'd also like this feature to be implemented. In my case, it is impractical to use subdomains and would really like to be able to serve actual from a different location than /.
