### ISSUE TITLE
[Feature] Allow “payee/category/account contains” in rules

### ISSUE THREAD

**Issue by j-f1** [actualbudget/actual#679]
These are supported in the filter UI of a transaction table, but they are not available for rules.

**Comment by themadman0980** [comment]
Perhaps a simpler way to handle this could be the addition of an "AND" / "OR option box at the top, so that users can pick to use all of the listed conditions or any of them? This may cause issues if you want anything complicated, but should help with basic use cases.

In the image below, this would change the fixed "If ALL these conditions match" to "If ALL/ANY OF these conditions match".

![image](https://user-images.githubusercontent.com/107305060/220827597-d5724ca6-0bfd-4104-88a4-238f5f3d191e.png)

**Comment by themadman0980** [comment]
If you wanted to get *really* fancy, something like the Plex interface would be incredible. I imagine this would take a fair bit of work to overhaul though?

![image](https://user-images.githubusercontent.com/107305060/220828043-395fd7c9-1317-49e6-ab45-0c9ce4e37067.png)

**Comment by themadman0980** [comment]
I have moved the above idea to issue #546
