### ISSUE TITLE
Migrate from Glamor to Emotion

### ISSUE THREAD

**Issue by j-f1** [actualbudget/actual#701]
Glamor was last updated in 2017, and Emotion is a popular and actively maintained alternative that remains largely compatible with Glamor’s APIs.

**Comment by j-f1** [comment]
> The reason is that with React 18 and some of the work behind SSR/server components/concurrent features a lot of CSS-in-JS solutions out there are currently struggling.

Fortunately Actual is entirely a client rendered app (I don’t see server rendering as something that would make things much better given how the app is set up). Concurrent rendering could be nice but I also don’t think we would have a problem staying away from that if we wanted to.

> Also, any particular reason why we would prefer emotion to styled-components? SC is more popular and has better community support.

When I looked at styled-components, it seemed like we would need to change a ton of existing code, while Emotion is inspired by Glamor and therefore has a very similar API. (For example, I don’t think SC supports sub selectors using the object syntax?).

**Comment by maxichrome** [comment]
Just passing by on my way through an entirely unrelated issue on an unrelated project, to shed some light on this specific bit:

> (For example, I don’t think SC supports sub selectors using the object syntax?)

I edited the Style Objects example on styled-components' example to contain a child and it seems to work just fine:

<figure>
  <img alt="Style Objects documentation with an edited example showing a child component referenced in a style object via bracket notation reflecting its parent-defined style as expected" width="773" src="https://github.com/actualbudget/actual/assets/33473181/c51632c2-387f-4fa6-82ab-3a383a1f1b40" />
  <figcaption>Here, the child component has been modified by its parent to show yellow text instead of the child's self-defined red.</figcaption>
</figure>

**Comment by youngcw** [comment]
@joel-jeremy Can this be closed now?

**Comment by youngcw** [comment]
completed by #3471
