### ISSUE TITLE
Recreate node-libofx build logic from scratch

### ISSUE THREAD

**Issue by j-f1** [actualbudget/actual#798]
Currently, there is some code in the `packages/node-libofx` directory that builds the C++ code into a Wasm file using emscripten. It does not work. I think the whole thing needs to be deleted and rebuilt from scratch — I spent several hours on trying to get things working yesterday and was thoroughly unsuccessful. 

Issues:

- https://github.com/llvm/llvm-project/issues/61555
- https://github.com/emscripten-core/emscripten/issues/10719
- Probably other things?

Some options to potentially explore:

- wait for the above issues to be fixed
- update the C++ projects to the latest version and hope for the best
- Use [Zig](https://ziglang.org/)’s build system instead of the existing makefiles?
- Maybe write a wrapper in Rust and give their build system a try?

This is a blocker for debugging issues like #794.

**Comment by Shazib** [comment]
There are a couple of other projects that implement OFX in js, is it worth exploring these as alternatives?

[Libofxjs ](https://github.com/clarete/libofxjs) uses the same C++ library underneath, but uses node-gyp instead of emscripten, which we use anyway with better-sqlite3 etc, so perhaps we could drop the need to emscripten entirely.

There are also various pure JS implementations but these might require a bit more work to migrate and regression test.

**Comment by j-f1** [comment]
Would libofxjs work in the browser?

@sinistersnare contributed an experimental new OFX importer in #921, which we’re currently waiting for feedback on.
