### ISSUE TITLE
[Bug]: Import of CSV containing extra newline breaks CSV field select dropdowns

### ISSUE THREAD

**Issue by zzzachzzz** [actualbudget/actual#846]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue

### What happened?

When attempting to import a csv, if the csv contains an extra blank line at the end of the file, the CSV field selector dropdowns only offer the first column as a possible selection.

To reproduce, take a valid csv to import, add a newline to the end of the file, attempt an import, and see that only the first column is offered to be selected.

![image](https://user-images.githubusercontent.com/14324200/229390291-7813d865-d910-4b16-883a-c5259db69c94.png)

### Where are you hosting Actual?

Docker

### What browsers are you seeing the problem on?

Chrome

### Operating System

Linux

**Comment by MatissJanis** [comment]
👋 Thanks for the bug report! Would you mind providing an example CSV file showcasing the issue?

**Comment by zzzachzzz** [comment]
Yes, here you go. You'll find that removing the blank newline at the end of the file will fix the issue.
[repro-846.csv](https://github.com/actualbudget/actual/files/11183788/repro-846.csv)

**Comment by aaroneiche** [comment]
I can replicate the issue. I think what we're seeing here is that that CSV data is essentially invalid - because the CSV format establishes that an empty new line is the end of the data, a previous empty line is basically a row that doesn't have any delimiters.

While we can try to accommodate an extra line at the end of the file, it's much more practical (I think) to simply display a warning that the data is invalid. In fact, an error is already displayed - just perhaps not obvious enough that it can't be handled:
 
<img width="787" alt="CSVError" src="https://user-images.githubusercontent.com/262515/232675218-1a3eea0d-bffb-42c3-a9c3-f4c2a17d5654.png">
I'm guessing the error row shows up first because it's reverse chronological order.

**Comment by aaroneiche** [comment]
Scratch my last - CSV data with bad rows don't exhibit the issue - only when there's a bad row before the end of the file newline. I'll look a little deeper at the cause.
