### ISSUE TITLE
[Feature] Would you be interested in a helm chart? 

### ISSUE THREAD

**Issue by gorrilla10101** [actualbudget/actual#875]
### Verified feature request does not already exist?

- [X] I have searched and found no existing issue

### 💻

- [X] Would you like to implement this feature?

### Pitch: what problem are you trying to solve?

Helm charts make it  easier to deploy things into kubernetes clusters. I use k3s instead of docker compose. As part of setting this up I created a heml chart. I would be willing to hand it over so that it could be made official and maintained with the application. 

### Teaching and learning

Add documentation directing people to the helm charts and highlight any extra configuration needed if necessary.

**Comment by Daemonslayer2048** [comment]
If this end up being of interest I also use K8s at home on RKE2 I would be happy to help/participate!

**Comment by j-f1** [comment]
Is there a way the helm chart could be hosted and maintained in some sort of centralized repository? I don‘t think any of the current maintainers have k3s/k8s experience so we would not be able to handle bug fixes / periodic maintenance. Because of that we are reluctant to include anything directly in the repository, but we would be happy to link to such a configuration from our docs.

We are definitely open to discussion about how best to do this so don’t let me closing the issue discourage you :)

**Comment by Daemonslayer2048** [comment]
I don't want to revive the conversation if you dont want it to be. Is there a place you would rather us discuss this idea?
