### ISSUE TITLE
[Bug]: (By design or bug) Clicking "X uncategorized transactions" shows list of transactions in all accounts even if user is in single account view at the moment of click

### ISSUE THREAD

**Issue by mkalamarz** [actualbudget/actual#905]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue

### What happened?

As in title, I'm not sure if this is intended behavior or a bug.

To reproduce:
1. Have at least 2 accounts with at least 1 uncategorized transaction in each (them being "For budget" shouldn't matter).
2. Click on one of the accounts, which will show the list of transactions associated with it.
3. In the top right corner click "X uncategorized transactions".
4. Even though you were in a specific account view, now you see all the uncategorized transactions (in all accounts)

ALSO in step 2. you can select either a single account or "For budget" or "All accounts".

Weirdly enough in step 4. a completly new type of view (I guess this is called an endpoint?) is forced: **accounts/uncategorized**. First I thought it simple redirected me to a filtered **/accounts**.

I would assume this is by design as the number "X" always depicts all uncategorized transactions no matter if a single account or "For budget" or "All accounts" is selected. Also because it always redirects to **accounts/uncategorized**.

From a UX perspective I would expect to be left in the same "view" and simply get something like a filter "Category is (nothing)" applied to it (it wouldn't work because of #901).

### What error did you receive?

No error.

### Where are you hosting Actual?

Fly.io

### What browsers are you seeing the problem on?

Firefox

### Operating System

Windows 10

**Comment by mkalamarz** [comment]
@j-f1 Bump 🤛 (I know that some issues are more pressing than others but maybe consider adding automation that would ping "someone" or add tag e.x. "stale" when "bug" and "needs triage" are present for more than 2 (?) weeks since posting?)

**Comment by trevdor** [comment]
@mkalamarz 'Tis a busy project. But I gotcha:

The behaviors you describe are all as designed, though I see how it could be confusing. The workflow is for where you want to tidy up ALL the transactions you have yet to categorize in your budget, since that's the only way to be sure your budget reflects current reality.

I'd have to ponder it some more, but at first blush, I think jumping to `/accounts/budgeted` with a filter instead of a special screen at `accounts/uncategorized` could be a fabulous enhancement and a good way to highlight our filter capabilities. Essentially, this:

<img width="827" alt="Screenshot 2023-05-10 at 3 19 28 PM" src="https://github.com/actualbudget/actual/assets/5862724/1e16d699-aa1e-496a-89a4-b21e7a8734bd">

Still, definitely a new feature, not a bug.

**Comment by mkalamarz** [comment]
@trevdor This issue has title and description worded as a bug report, so I have created a proper feature request (#1030). Could you please remove the "needs votes" + "feature" tags and bot message while adding (I guess) "wontfix" for no future confusion?
