### ISSUE TITLE
[Bug] Split transaction handling needs improvements

### ISSUE THREAD

**Issue by mekkanik** [actualbudget/actual#91]
Currently, as soon as the split option is selected in the category column, the keyboard focus switches to the newly added split row. This breaks the flow of data entry. Focus should move to the Outflow column instead.

**Comment by vkbytes** [comment]
+1, I was quite confused with this and i had to do a couple of times to get it right.

**Comment by tjfinlinson** [comment]
This would a nice thing to fix so you can stay in the right flow. If I knew how to do this I'd take this on. Justification would be that you really don't want to start entering split lines until you have entered the total amount for the transaction so that actual will calculate the remaining amounts for you as you enter the splits.

**Comment by trevdor** [comment]
I lean heavily on that auto-remainder logic myself, @tjfinlinson! I’ve also imagined a power user shortcut for moving what’s remaining into the outflow/inflow column instead of manually typing what I see there for my last split.

I’d love to hear @jlongster’s take on the entry flow, since I expect he gave this a lot of thought.

**Comment by j-f1** [comment]
Some thoughts on this interaction:
- if there isn’t an amount specified in the parent when the split transaction is selected, focus should move to the “Payment” column of the parent rather than the category of the first child split transaction
- when tabbing into the payment/deposit column, it should be prefilled with the remaining value. Typing should erase that default and let you type a custom value, or you could e.g. type <kbd>&rarr;</kbd> <kbd>/</kbd> <kbd>2</kbd> to put half of the amount into that part of the split

**Comment by MatissJanis** [comment]
Fix: https://github.com/actualbudget/actual/pull/999
