### ISSUE TITLE
[Feature] Template Priorities

### ISSUE THREAD

**Issue by youngcw** [actualbudget/actual#959]
### Verified feature request does not already exist?

- [X] I have searched and found no existing issue

### 💻

- [ ] Would you like to implement this feature?

### Pitch: what problem are you trying to solve?

Option to add priorities to the templates.  When applying the templates the higher priority categories would be filled in first, and only filled in if there is enough money available to apply the whole template amount.

Current template logic ignores available funds and can apply more than is available.  Adding priorities would make the templates be usable by more categories that are filled in after the required stuff like bills, mortgage, etc.

I believe this would work with the existing logic with only the sorting and funds check added.

I can invision some cool use cases with multiple template lines with varying priorities in a single category.

### Describe your ideal solution to this problem

When processing the templates do the following:
1. Sort templates by reading the priority field (no listed priority would default to highest priority)
2. apply next template:
a. check if enough funds are available (ignore if no priority listed to retain current functionality)
b. apply template to category budget
4. loop back to 2 unless finished

### Teaching and learning

Add priority option information to docs

**Comment by shall0pass** [comment]
Interesting.  We could either add a keyword to the end of the string, or my preference would be something like #target-1, #target-2, #target-3 for the beginning of the string instead of #template, where the integer at the end of the string defines the priority level.  We could also add notification pop ups if sufficient funds aren't available to fund all targets.

I think it's a good idea.

**Comment by youngcw** [comment]
I think it makes the most sense to me to do it like #template-X or similar.  That way its the same prefix for everything.  I also think that adding the number to the template tag makes it more clear that it works with all template types.

I was playing with the pegjs parser last night and I couldn't get the regular expression changed properly on the percent template to not pull in an at-the-end priority flag to the category name, but its trivial to add a priority to the beginning of each type.  Someone more versed in regex would probably have no issues getting a flag at the end of the template working though.

**Comment by shall0pass** [comment]
I'm playing with it too.  It's mostly working, except I broke the compounding with multiple templates.  I'm still thinking around that issue.  My current changes use the #template-1 expression.  I've posted my progress.  Maybe it's an example of what not to do to allow templates to compound with priorities.  Currently it makes three passes at applying templates, which is why the compounding doesn't work.  I haven't figured out a good way to indicate if I should use the previously budgeted cell or not.  I think line 47 is where my decision point needs to be.

https://github.com/shall0pass/actual/tree/priorityGoals

**Comment by youngcw** [comment]
I made a parser that pulls out a priority and adds it to the parsed fields.  It works with any number and doesn't require hand coding priority numbers.  It should also not pass back null priority and set a default of 0.

https://github.com/youngcw/actual/tree/priority_template

Feel free to use it.

**Comment by shall0pass** [comment]
The bit that I seem to be stuck on is that currently the logic runs through each of the templates for a specific category all at once.  With priorities, we have to be able to calculate a category, apply and exit that calculation, then re-enter  and add additional funds if available in lower priority levels.  How do we know if we're in the first time through the category or the third since not all categories will have a high priority?  It matters when we have to either add the initial budgeted value to the calculation or overwrite by starting from 0.

**Comment by youngcw** [comment]
Would it be useful for testing to overwrite amounts by default on start and then add up as you go down the priority list?  

Maybe at some point an invisible flag can be set for manual changes to the budgeted amount, and if there isn't a flag then all the templates can just be added again with currently available funds.

Personally I would be ok with not differentiating between apply and overwrite of the templates so its overwrite always.  But that may be confusing for other people.

**Comment by shall0pass** [comment]
See what you think about what I have now.  I used your peggy updates :)  This forces an overwrite using templates, so that feature goes away unless someone can find a way around it.  It wouldn't bother me.  It also allows partial funding of templates at the end of the script which may or may not be preferred.  I **think** it's working.
