### ISSUE TITLE
[Bug]: Multiple Schedule Templates not calculating budget correctly

### ISSUE THREAD

**Issue by lexieheinle** [actualbudget/actual#970]
### Verified issue does not already exist?

- [X] I have searched and found no existing issue

### What happened?

For a specific category, I have both bimonthly (every 2 months) transactions and an annual transaction. Therefore, the category's total scheduled transactions for June is $151.22, and the June's category balance is $134.90. However, clicking Apply budget template doesn't budget $16.32  ($151.22-$134.90) as I would expect but $0.

**Current behavior:**
1. Created every 2 months Schedule1 for 6/10 $65.42 and annual Schedule2 for 6/10 $85.80.
2. Set category's note to:
 ```
#template schedule Schedule1
#template schedule Schedule2
```
3. Click Apply budget template for June.
4. Nothing is budgeted.

**Expected behavior:**
Category's Budgeted would be $16.32.

Client version: v23.4.2
Server version v23.4.2

### Where are you hosting Actual?

Fly.io

### What browsers are you seeing the problem on?

Chrome

### Operating System

Mac OSX

**Comment by youngcw** [comment]
I tried to recreate this and it looks like that since the available budgeted amount is already greater than either of the schedules individually neither get applied.

I am seeing that if the starting balance in the category isn't zero, then multiple schedule templates is broken.  It works fine if it starts off with 0 in the category.

**Comment by shall0pass** [comment]
The same problem used to happen with 'by' matches.  The problem with multiple templates in the 'by' format or the 'schedule' format is that there are always more variables than there are equations, so it's extremely difficult to do the calculations in the middle of the cycles when there is already money budgeted.  The 'by' matches were moved to an average of the total required over those periods.  Since the format `#template 100 by 2023-06` is essentially the same as having a schedule for 100 in June, I think the averaging approach will need to be implemented for schedules too.  Unfortunately, because it's averaged the amounts budgeted won't be what you expect if you budget them separately in different categories so you may not be totally content with this proposal.

**Comment by shall0pass** [comment]
If you get a chance, could you try out the PR to see if this would fix the issue?
