### ISSUE TITLE
[Feature] Plugin system

### ISSUE THREAD

**Issue by JazzaG** [actualbudget/actual#973]
### Verified feature request does not already exist?

- [X] I have searched and found no existing issue

### 💻

- [X] Would you like to implement this feature?

### Pitch: what problem are you trying to solve?

Extending on the [planned API](https://actualbudget.github.io/docs/Developers/API), a modular plugin system would allow users to add extra functionality to Actual while not bloating the application for users who only need a simple budgeting tool.

Potential plugin ideas might include:
- custom importers; many banks and financial institutions around the world haven't entered the 21st century and may not provide ways to export transactions, or don't provide files compatible with Actual's importer, or are not supported by Nordigen
- niche reports
- email/push notifications for upcoming transactions
- [IFTTT](https://ifttt.com/) integration 

As this feature matures, plugins could support superfluous functionality like theming to allow users to further customise their Actual instance.

Feature requests such as #805, #730, and #737 could be supported with plugins.

---

In my specific case, I've had to write a program to convert my bank statement PDF into a CSV file so that it could be imported into Actual. I'm looking forward to the release of the API so it can further be automated, but a plugin system would allow me to add this functionality directly into Actual, and I'll be able to share it with other users who would find it useful.

### Describe your ideal solution to this problem

See other applications that allows users to extend functionality ([Wordpress](https://developer.wordpress.org/plugins/intro/),  [Discord](https://discord.com/developers/docs/intro))

Plugins would be written in Javascript/Typescript to take advantage of the [Actual API](https://actualbudget.github.io/docs/Developers/API). They could be packaged up into a .zip file to be uploaded to some `/plugins` directory. This directory could be mounted as a Docker volume.

Actual could implement a hook/events system to send data to all installed plugins. For example, loading the Reports page may trigger an event which is picked up by a plugin to then generate a custom report to send back to Actual for rendering.

Plugins could have a dedicated page under the More section of the sidebar menu. A custom importer plugin may have a page to add an API key for a bank. A custom reports plugin may have a page to customise data shown in the report.

### Teaching and learning

A plugins page could be added to the Settings page or it could have its own page under the More section in the sidebar. This plugins page would allow users to view installed plugins, remove plugins, and have a form to upload plugins.

Developer documentation would need to written to provide info on plugin development.

**Comment by j-f1** [comment]
This is a really interesting idea! I don’t think we will implement it in the near future because:

- For many tasks, the existing API will work just fine (such as custom importers as long as you’re ok with doing the import via a different interface).
- For things like custom reports, they would likely want to build off of our existing component library so that they fit in with the rest of the app. But that would require us to stabilize and document our component APIs which I don’t think would be worth the time we’d need to put in or the degree to which it would limit our flexibility to make breaking changes to our components.
- There is currently no reporting of actions to the server side besides the regular syncing of changes in bulk. We would need to write and maintain code for scanning incoming changes and forwarding them onto plugins.

It would be great if you were willing to share your code for doing the import! I think having a few projects that use the API would make it much easier for others to get started.

We are aware that the API package does not currently work with budgets that have been opened in the latest version of Actual. It should work with older budgets in the meantime if you want to test, and we are planning to do a release of all packages soon. We’re also planning to release the API package more often in the future to prevent that from happening again.
